MODULE=CPingPongKripke

ALL_TARGETS=host-local

HDRS+=CPingPongKripke.h
C_SRCS=CPingPongKripke.c CPingPongKripke_META.c
SPECIFIC_CFLAGS+=-I../../..
SPECIFIC_LIBS=-lclfsm

SOPREFIX=
.include "../../../../../../mk/mipal.mk"	# comes last!
