#
#	$Id$
#
# Makefile for pre- and cross-compiling .machine files
#
MACHINES=SpeedTest

.include "../../../../mk/fsm.mk"	# comes first: required for fsms
.include "../../../../mk/mipal.mk"	# comes last!
