#
#	$Id$
#
# Makefile for pre- and cross-compiling .machine files
#
MACHINES=StateMachineStarter SMGameController SMBallFollower SMButtonChest SMButtonLeftFoot SMButtonRightFoot SMGetUp SMHeadBallTracker SMHeadScanner SMLeftFootControl SMPlayer SMRobotPosition SMWalkScanner

.include "../../../../../mk/fsm.mk"	# comes first: required for compiling state machines

.include "../../../../../mk/mipal.mk"	# comes last!
