/** \file
 *  This C source file was generated by $ANTLR version 3.4
 *
 *     -  From the grammar source file : /Users/Robert/src/MiPal/GUNao/posix/gufsm/qfsm2gu/../LANGUAGE/ActionsContainer.g
 *     -                            On : 2011-12-15 13:57:52
 *     -                for the parser : ActionsContainerParserParser
 *
 * Editing it, at least manually, is not wise.
 *
 * C language generator and runtime by Jim Idle, jimi|hereisanat|idle|dotgoeshere|ws.
 *
 *
*/
// [The "BSD license"]
// Copyright (c) 2005-2009 Jim Idle, Temporal Wave LLC
// http://www.temporal-wave.com
// http://www.linkedin.com/in/jimidle
//
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
// 1. Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
// 2. Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
// 3. The name of the author may not be used to endorse or promote products
//    derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
// IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
// OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
// INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
// NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
// THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

/* -----------------------------------------
 * Include the ANTLR3 generated header file.
 */
#include    "ActionsContainerParser.h"
/* ----------------------------------------- */





/* MACROS that hide the C interface implementations from the
 * generated code, which makes it a little more understandable to the human eye.
 * I am very much against using C pre-processor macros for function calls and bits
 * of code as you cannot see what is happening when single stepping in debuggers
 * and so on. The exception (in my book at least) is for generated code, where you are
 * not maintaining it, but may wish to read and understand it. If you single step it, you know that input()
 * hides some indirect calls, but is always referring to the input stream. This is
 * probably more readable than ctx->input->istream->input(snarfle0->blarg) and allows me to rejig
 * the runtime interfaces without changing the generated code too often, without
 * confusing the reader of the generated output, who may not wish to know the gory
 * details of the interface inheritance.
 */

#define		CTX	ctx

/* Aids in accessing scopes for grammar programmers
 */
#undef	SCOPE_TYPE
#undef	SCOPE_STACK
#undef	SCOPE_TOP
#define	SCOPE_TYPE(scope)   pActionsContainerParser_##scope##_SCOPE
#define SCOPE_STACK(scope)  pActionsContainerParser_##scope##Stack
#define	SCOPE_TOP(scope)    ctx->pActionsContainerParser_##scope##Top
#define	SCOPE_SIZE(scope)		ctx->pActionsContainerParser_##scope##Stack_limit
#define SCOPE_INSTANCE(scope, i)	(ctx->SCOPE_STACK(scope)->get(ctx->SCOPE_STACK(scope),i))

/* Macros for accessing things in the parser
 */

#undef	    PARSER
#undef	    RECOGNIZER
#undef	    HAVEPARSEDRULE
#undef		MEMOIZE
#undef	    INPUT
#undef	    STRSTREAM
#undef	    HASEXCEPTION
#undef	    EXCEPTION
#undef	    MATCHT
#undef	    MATCHANYT
#undef	    FOLLOWSTACK
#undef	    FOLLOWPUSH
#undef	    FOLLOWPOP
#undef	    PRECOVER
#undef	    PREPORTERROR
#undef	    LA
#undef	    LT
#undef	    CONSTRUCTEX
#undef	    CONSUME
#undef	    MARK
#undef	    REWIND
#undef	    REWINDLAST
#undef	    PERRORRECOVERY
#undef	    HASFAILED
#undef	    FAILEDFLAG
#undef	    RECOVERFROMMISMATCHEDSET
#undef	    RECOVERFROMMISMATCHEDELEMENT
#undef		INDEX
#undef      ADAPTOR
#undef		SEEK
#undef	    RULEMEMO
#undef		DBG

#define	    PARSER				ctx->pParser
#define	    RECOGNIZER				PARSER->rec
#define	    PSRSTATE				RECOGNIZER->state
#define	    HAVEPARSEDRULE(r)			RECOGNIZER->alreadyParsedRule(RECOGNIZER, r)
#define	    MEMOIZE(ri,si)			RECOGNIZER->memoize(RECOGNIZER, ri, si)
#define	    INPUT				PARSER->tstream
#define	    STRSTREAM				INPUT
#define	    ISTREAM				INPUT->istream
#define	    INDEX()				ISTREAM->index(INPUT->istream)
#define	    HASEXCEPTION()			(PSRSTATE->error == ANTLR3_TRUE)
#define	    EXCEPTION				PSRSTATE->exception
#define	    MATCHT(t, fs)			RECOGNIZER->match(RECOGNIZER, t, fs)
#define	    MATCHANYT()				RECOGNIZER->matchAny(RECOGNIZER)
#define	    FOLLOWSTACK				PSRSTATE->following
#ifdef  SKIP_FOLLOW_SETS
#define	    FOLLOWPUSH(x)
#define	    FOLLOWPOP()
#else
#define	    FOLLOWPUSH(x)			FOLLOWSTACK->push(FOLLOWSTACK, ((void *)(&(x))), NULL)
#define	    FOLLOWPOP()				FOLLOWSTACK->pop(FOLLOWSTACK)
#endif
#define	    PRECOVER()				RECOGNIZER->recover(RECOGNIZER)
#define	    PREPORTERROR()			RECOGNIZER->reportError(RECOGNIZER)
#define	    LA(n)				INPUT->istream->_LA(ISTREAM, n)
#define	    LT(n)				INPUT->_LT(INPUT, n)
#define	    CONSTRUCTEX()			RECOGNIZER->exConstruct(RECOGNIZER)
#define	    CONSUME()				ISTREAM->consume(ISTREAM)
#define	    MARK()				ISTREAM->mark(ISTREAM)
#define	    REWIND(m)				ISTREAM->rewind(ISTREAM, m)
#define	    REWINDLAST()			ISTREAM->rewindLast(ISTREAM)
#define	    SEEK(n)				ISTREAM->seek(ISTREAM, n)
#define	    PERRORRECOVERY			PSRSTATE->errorRecovery
#define	    FAILEDFLAG				PSRSTATE->failed
#define	    HASFAILED()				(FAILEDFLAG == ANTLR3_TRUE)
#define	    BACKTRACKING			PSRSTATE->backtracking
#define	    RECOVERFROMMISMATCHEDSET(s)		RECOGNIZER->recoverFromMismatchedSet(RECOGNIZER, s)
#define	    RECOVERFROMMISMATCHEDELEMENT(e)	RECOGNIZER->recoverFromMismatchedElement(RECOGNIZER, s)
#define     ADAPTOR                         ctx->adaptor
#define		RULEMEMO						PSRSTATE->ruleMemo
#define		DBG								RECOGNIZER->debugger


#define		TOKTEXT(tok, txt)				tok, (pANTLR3_UINT8)txt

/* The 4 tokens defined below may well clash with your own #defines or token types. If so
 * then for the present you must use different names for your defines as these are hard coded
 * in the code generator. It would be better not to use such names internally, and maybe
 * we can change this in a forthcoming release. I deliberately do not #undef these
 * here as this will at least give you a redefined error somewhere if they clash.
 */
#define	    UP	    ANTLR3_TOKEN_UP
#define	    DOWN    ANTLR3_TOKEN_DOWN
#define	    EOR	    ANTLR3_TOKEN_EOR
#define	    INVALID ANTLR3_TOKEN_INVALID


/* =============================================================================
 * Functions to create and destroy scopes. First come the rule scopes, followed
 * by the global declared scopes.
 */



/* ============================================================================= */

/* =============================================================================
 * Start of recognizer
 */


/** \brief Table of all token names in symbolic order, mainly used for
 *         error reporting.
 */
pANTLR3_UINT8   ActionsContainerParserTokenNames[36+4]
     = {
        (pANTLR3_UINT8) "<invalid>",       /* String to print to indicate an invalid token */
        (pANTLR3_UINT8) "<EOR>",
        (pANTLR3_UINT8) "<DOWN>",
        (pANTLR3_UINT8) "<UP>",
        (pANTLR3_UINT8) "ARG_DEF",
        (pANTLR3_UINT8) "BLOCK",
        (pANTLR3_UINT8) "EOL",
        (pANTLR3_UINT8) "EscapeSequence",
        (pANTLR3_UINT8) "FUNC_DECL",
        (pANTLR3_UINT8) "FUNC_DEF",
        (pANTLR3_UINT8) "FUNC_HDR",
        (pANTLR3_UINT8) "INTERNALPART",
        (pANTLR3_UINT8) "K_ANDAND",
        (pANTLR3_UINT8) "K_CHAR",
        (pANTLR3_UINT8) "K_COMMA",
        (pANTLR3_UINT8) "K_EQ",
        (pANTLR3_UINT8) "K_EQEQ",
        (pANTLR3_UINT8) "K_FOR",
        (pANTLR3_UINT8) "K_ID",
        (pANTLR3_UINT8) "K_INT",
        (pANTLR3_UINT8) "K_INT_TYPE",
        (pANTLR3_UINT8) "K_LCURLY",
        (pANTLR3_UINT8) "K_LCURVE",
        (pANTLR3_UINT8) "K_LT",
        (pANTLR3_UINT8) "K_MINUS",
        (pANTLR3_UINT8) "K_NOT",
        (pANTLR3_UINT8) "K_OROR",
        (pANTLR3_UINT8) "K_PLUS",
        (pANTLR3_UINT8) "K_RCURLY",
        (pANTLR3_UINT8) "K_RCURVE",
        (pANTLR3_UINT8) "K_SEMICOLON",
        (pANTLR3_UINT8) "K_VOID",
        (pANTLR3_UINT8) "ONENTRY",
        (pANTLR3_UINT8) "ONEXIT",
        (pANTLR3_UINT8) "STATEMENT_LIST",
        (pANTLR3_UINT8) "STATENAME",
        (pANTLR3_UINT8) "STRING_GUTS",
        (pANTLR3_UINT8) "STRING_LITERAL",
        (pANTLR3_UINT8) "VAR_DEF",
        (pANTLR3_UINT8) "WS"
       };



// Forward declare the locally static matching functions we have generated.
//
static 
 ActionsContainerParser_actions_return
	actions    (pActionsContainerParser ctx);
static 
 ActionsContainerParser_state_description_return
	state_description    (pActionsContainerParser ctx);
static 
 ActionsContainerParser_description_return
	description    (pActionsContainerParser ctx);
static 
 ActionsContainerParser_onEntry_part_return
	onEntry_part    (pActionsContainerParser ctx);
static 
 ActionsContainerParser_onExit_part_return
	onExit_part    (pActionsContainerParser ctx);
static 
 ActionsContainerParser_internal_part_return
	internal_part    (pActionsContainerParser ctx);
static 
 ActionsContainerParser_state_name_return
	state_name    (pActionsContainerParser ctx);
static 
 ActionsContainerParser_state_id_return
	state_id    (pActionsContainerParser ctx);
static void	ActionsContainerParserFree(pActionsContainerParser ctx);
static void     ActionsContainerParserReset (pActionsContainerParser ctx);

// Delegated rules
//
static 
 ActionsContainer_SimpleCParser_forStat_return
 forStat(pActionsContainerParser ctx);
static 
 ActionsContainer_SimpleCParser_declaration_return
 declaration(pActionsContainerParser ctx);
static 
 ActionsContainer_SimpleCParser_formalParameter_return
 formalParameter(pActionsContainerParser ctx);
static 
 ActionsContainer_SimpleCParser_statement_return
 statement(pActionsContainerParser ctx);
static 
 ActionsContainer_SimpleCParser_functionHeader_return
 functionHeader(pActionsContainerParser ctx);
static 
 ActionsContainer_SimpleCParser_expr_return
 expr(pActionsContainerParser ctx);
static 
 ActionsContainer_SimpleCParser_declarator_return
 declarator(pActionsContainerParser ctx);
static 
 ActionsContainer_SimpleCParser_condExpr_return
 condExpr(pActionsContainerParser ctx);
static 
 ActionsContainer_SimpleCParser_aexpr_return
 aexpr(pActionsContainerParser ctx);
static 
 ActionsContainer_SimpleCParser_functionCallOrVariable_return
 functionCallOrVariable(pActionsContainerParser ctx);
static 
 ActionsContainer_SimpleCParser_literal_return
 literal(pActionsContainerParser ctx);
static 
 ActionsContainer_SimpleCParser_program_return
 program(pActionsContainerParser ctx);
static 
 ActionsContainer_SimpleCParser_assignStat_return
 assignStat(pActionsContainerParser ctx);
static 
 ActionsContainer_SimpleCParser_atom_return
 atom(pActionsContainerParser ctx);
static 
 ActionsContainer_SimpleCParser_variable_return
 variable(pActionsContainerParser ctx);
static 
 ActionsContainer_SimpleCParser_block_return
 block(pActionsContainerParser ctx);
static 
 ActionsContainer_SimpleCParser_type_return
 type(pActionsContainerParser ctx);


/* For use in tree output where we are accumulating rule labels via label += ruleRef
 * we need a function that knows how to free a return scope when the list is destroyed.
 * We cannot just use ANTLR3_FREE because in debug tracking mode, this is a macro.
 */
static	void ANTLR3_CDECL freeScope(void * scope)
{
    ANTLR3_FREE(scope);
}

/** \brief Name of the grammar file that generated this code
 */
static const char fileName[] = "/Users/Robert/src/MiPal/GUNao/posix/gufsm/qfsm2gu/../LANGUAGE/ActionsContainer.g";

/** \brief Return the name of the grammar file that generated this code.
 */
static const char * getGrammarFileName()
{
	return fileName;
}
/** \brief Create a new ActionsContainerParser parser and return a context for it.
 *
 * \param[in] instream Pointer to an input stream interface.
 *
 * \return Pointer to new parser context upon success.
 */
ANTLR3_API pActionsContainerParser
ActionsContainerParserNew   (pANTLR3_COMMON_TOKEN_STREAM instream)
{
	// See if we can create a new parser with the standard constructor
	//
	return ActionsContainerParserNewSSD(instream, NULL);
}

/** \brief Create a new ActionsContainerParser parser and return a context for it.
 *
 * \param[in] instream Pointer to an input stream interface.
 *
 * \return Pointer to new parser context upon success.
 */
ANTLR3_API pActionsContainerParser
ActionsContainerParserNewSSD   (pANTLR3_COMMON_TOKEN_STREAM instream, pANTLR3_RECOGNIZER_SHARED_STATE state)
{
    pActionsContainerParser ctx;	    /* Context structure we will build and return   */

    ctx	= (pActionsContainerParser) ANTLR3_CALLOC(1, sizeof(ActionsContainerParser));

    if	(ctx == NULL)
    {
		// Failed to allocate memory for parser context
		//
        return  NULL;
    }

    /* -------------------------------------------------------------------
     * Memory for basic structure is allocated, now to fill in
     * the base ANTLR3 structures. We initialize the function pointers
     * for the standard ANTLR3 parser function set, but upon return
     * from here, the programmer may set the pointers to provide custom
     * implementations of each function.
     *
     * We don't use the macros defined in ActionsContainerParser.h here, in order that you can get a sense
     * of what goes where.
     */

    /* Create a base parser/recognizer, using the supplied token stream
     */
    ctx->pParser	    = antlr3ParserNewStream(ANTLR3_SIZE_HINT, instream->tstream, state);
    /* Install the implementation of our ActionsContainerParser interface
     */
    ctx->actions	= actions;
    ctx->state_description	= state_description;
    ctx->description	= description;
    ctx->onEntry_part	= onEntry_part;
    ctx->onExit_part	= onExit_part;
    ctx->internal_part	= internal_part;
    ctx->state_name	= state_name;
    ctx->state_id	= state_id;
	// Install the delegated methods so that they appear to be a part of this
	// parser
	//
    ctx->forStat	= forStat;
    ctx->declaration	= declaration;
    ctx->formalParameter	= formalParameter;
    ctx->statement	= statement;
    ctx->functionHeader	= functionHeader;
    ctx->expr	= expr;
    ctx->declarator	= declarator;
    ctx->condExpr	= condExpr;
    ctx->aexpr	= aexpr;
    ctx->functionCallOrVariable	= functionCallOrVariable;
    ctx->literal	= literal;
    ctx->program	= program;
    ctx->assignStat	= assignStat;
    ctx->atom	= atom;
    ctx->variable	= variable;
    ctx->block	= block;
    ctx->type	= type;

    ctx->free			= ActionsContainerParserFree;
    ctx->reset			= ActionsContainerParserReset;
    ctx->getGrammarFileName	= getGrammarFileName;

    /* Install the scope pushing methods.
     */
ADAPTOR	= ANTLR3_TREE_ADAPTORNew(instream->tstream->tokenSource->strFactory);

ctx->vectors	= antlr3VectorFactoryNew(0);
	// Initialize the parsers that we are going to delegate some
	// functions to.
	//
	ctx->gSimpleCParser = ActionsContainer_SimpleCParserNewSSD(instream, PSRSTATE, ctx);
    /* Install the token table
     */
    PSRSTATE->tokenNames   = ActionsContainerParserTokenNames;


    /* Return the newly built parser to the caller
     */
    return  ctx;
}

static void
ActionsContainerParserReset (pActionsContainerParser ctx)
{
    RECOGNIZER->reset(RECOGNIZER);
}

/** Free the parser resources
 */
 static void
 ActionsContainerParserFree(pActionsContainerParser ctx)
 {
    /* Free any scope memory
     */

ctx->vectors->close(ctx->vectors);
/* We created the adaptor so we must free it
 */
ADAPTOR->free(ADAPTOR);

	// Free the parsers that we delegated to
	// functions to.NULL the state so we only free it once.
	//
	ctx->gSimpleCParser->pParser->rec->state = NULL;
	         ctx->gSimpleCParser->free(ctx->gSimpleCParser);
	// Free this parser
	//
    ctx->pParser->free(ctx->pParser);


    ANTLR3_FREE(ctx);

    /* Everything is released, so we can return
     */
    return;
 }

/** Return token names used by this 
parser

 *
 * The returned pointer is used as an index into the token names table (using the token
 * number as the index).
 *
 * \return Pointer to first char * in the table.
 */
static pANTLR3_UINT8    *getTokenNames()
{
        return ActionsContainerParserTokenNames;
}


/* Declare the bitsets
 */
/** Bitset defining follow set for error recovery in rule state: FOLLOW_state_description_in_actions37  */
static	ANTLR3_BITWORD FOLLOW_state_description_in_actions37_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000080042) };
static  ANTLR3_BITSET_LIST FOLLOW_state_description_in_actions37	= { FOLLOW_state_description_in_actions37_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_EOL_in_actions39  */
static	ANTLR3_BITWORD FOLLOW_EOL_in_actions39_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000080042) };
static  ANTLR3_BITSET_LIST FOLLOW_EOL_in_actions39	= { FOLLOW_EOL_in_actions39_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_state_id_in_state_description52  */
static	ANTLR3_BITWORD FOLLOW_state_id_in_state_description52_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000040000) };
static  ANTLR3_BITSET_LIST FOLLOW_state_id_in_state_description52	= { FOLLOW_state_id_in_state_description52_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_state_name_in_state_description54  */
static	ANTLR3_BITWORD FOLLOW_state_name_in_state_description54_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000040) };
static  ANTLR3_BITSET_LIST FOLLOW_state_name_in_state_description54	= { FOLLOW_state_name_in_state_description54_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_EOL_in_state_description56  */
static	ANTLR3_BITWORD FOLLOW_EOL_in_state_description56_bits[]	= { ANTLR3_UINT64_LIT(0x0000000100000000) };
static  ANTLR3_BITSET_LIST FOLLOW_EOL_in_state_description56	= { FOLLOW_EOL_in_state_description56_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_description_in_state_description58  */
static	ANTLR3_BITWORD FOLLOW_description_in_state_description58_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_description_in_state_description58	= { FOLLOW_description_in_state_description58_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_onEntry_part_in_description90  */
static	ANTLR3_BITWORD FOLLOW_onEntry_part_in_description90_bits[]	= { ANTLR3_UINT64_LIT(0x0000000200000000) };
static  ANTLR3_BITSET_LIST FOLLOW_onEntry_part_in_description90	= { FOLLOW_onEntry_part_in_description90_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_onExit_part_in_description92  */
static	ANTLR3_BITWORD FOLLOW_onExit_part_in_description92_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000200000) };
static  ANTLR3_BITSET_LIST FOLLOW_onExit_part_in_description92	= { FOLLOW_onExit_part_in_description92_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_internal_part_in_description94  */
static	ANTLR3_BITWORD FOLLOW_internal_part_in_description94_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_internal_part_in_description94	= { FOLLOW_internal_part_in_description94_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_ONENTRY_in_onEntry_part103  */
static	ANTLR3_BITWORD FOLLOW_ONENTRY_in_onEntry_part103_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000200000) };
static  ANTLR3_BITSET_LIST FOLLOW_ONENTRY_in_onEntry_part103	= { FOLLOW_ONENTRY_in_onEntry_part103_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_block_in_onEntry_part106  */
static	ANTLR3_BITWORD FOLLOW_block_in_onEntry_part106_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000040) };
static  ANTLR3_BITSET_LIST FOLLOW_block_in_onEntry_part106	= { FOLLOW_block_in_onEntry_part106_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_EOL_in_onEntry_part108  */
static	ANTLR3_BITWORD FOLLOW_EOL_in_onEntry_part108_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_EOL_in_onEntry_part108	= { FOLLOW_EOL_in_onEntry_part108_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_ONEXIT_in_onExit_part118  */
static	ANTLR3_BITWORD FOLLOW_ONEXIT_in_onExit_part118_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000200000) };
static  ANTLR3_BITSET_LIST FOLLOW_ONEXIT_in_onExit_part118	= { FOLLOW_ONEXIT_in_onExit_part118_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_block_in_onExit_part121  */
static	ANTLR3_BITWORD FOLLOW_block_in_onExit_part121_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000040) };
static  ANTLR3_BITSET_LIST FOLLOW_block_in_onExit_part121	= { FOLLOW_block_in_onExit_part121_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_EOL_in_onExit_part123  */
static	ANTLR3_BITWORD FOLLOW_EOL_in_onExit_part123_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_EOL_in_onExit_part123	= { FOLLOW_EOL_in_onExit_part123_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_block_in_internal_part132  */
static	ANTLR3_BITWORD FOLLOW_block_in_internal_part132_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_block_in_internal_part132	= { FOLLOW_block_in_internal_part132_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_K_ID_in_state_name151  */
static	ANTLR3_BITWORD FOLLOW_K_ID_in_state_name151_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_K_ID_in_state_name151	= { FOLLOW_K_ID_in_state_name151_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_K_INT_in_state_id159  */
static	ANTLR3_BITWORD FOLLOW_K_INT_in_state_id159_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_K_INT_in_state_id159	= { FOLLOW_K_INT_in_state_id159_bits, 1	};


/* ==============================================
 * Parsing rules
 */
/**
 * $ANTLR start actions
 * /Users/Robert/src/MiPal/GUNao/posix/gufsm/qfsm2gu/../LANGUAGE/ActionsContainer.g:9:1: actions : ( state_description ( EOL )* )+ ;
 */
static ActionsContainerParser_actions_return
actions(pActionsContainerParser ctx)
{
    ActionsContainerParser_actions_return retval;


    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    EOL2;
    ActionsContainerParser_state_description_return state_description1;
    #undef	RETURN_TYPE_state_description1
    #define	RETURN_TYPE_state_description1 ActionsContainerParser_state_description_return

    pANTLR3_BASE_TREE EOL2_tree;

    /* Initialize rule variables
     */

    root_0 = NULL;

    EOL2       = NULL;
    state_description1.tree = NULL;
    retval.start = LT(1); retval.stop = retval.start;


    EOL2_tree   = NULL;


    retval.tree  = NULL;

    {
        // /Users/Robert/src/MiPal/GUNao/posix/gufsm/qfsm2gu/../LANGUAGE/ActionsContainer.g:9:8: ( ( state_description ( EOL )* )+ )
        // /Users/Robert/src/MiPal/GUNao/posix/gufsm/qfsm2gu/../LANGUAGE/ActionsContainer.g:9:10: ( state_description ( EOL )* )+
        {
            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));


            // /Users/Robert/src/MiPal/GUNao/posix/gufsm/qfsm2gu/../LANGUAGE/ActionsContainer.g:9:10: ( state_description ( EOL )* )+
            {
                int cnt2=0;

                for (;;)
                {
                    int alt2=2;
            	switch ( LA(1) )
            	{
            	case K_INT:
            		{
            			alt2=1;
            		}
            	    break;

            	}

            	switch (alt2)
            	{
            	    case 1:
            	        // /Users/Robert/src/MiPal/GUNao/posix/gufsm/qfsm2gu/../LANGUAGE/ActionsContainer.g:9:12: state_description ( EOL )*
            	        {
            	            FOLLOWPUSH(FOLLOW_state_description_in_actions37);
            	            state_description1=state_description(ctx);

            	            FOLLOWPOP();
            	            if  (HASEXCEPTION())
            	            {
            	                goto ruleactionsEx;
            	            }

            	            ADAPTOR->addChild(ADAPTOR, root_0, state_description1.tree);

            	            // /Users/Robert/src/MiPal/GUNao/posix/gufsm/qfsm2gu/../LANGUAGE/ActionsContainer.g:9:30: ( EOL )*

            	            for (;;)
            	            {
            	                int alt1=2;
            	                switch ( LA(1) )
            	                {
            	                case EOL:
            	                	{
            	                		alt1=1;
            	                	}
            	                    break;

            	                }

            	                switch (alt1)
            	                {
            	            	case 1:
            	            	    // /Users/Robert/src/MiPal/GUNao/posix/gufsm/qfsm2gu/../LANGUAGE/ActionsContainer.g:9:30: EOL
            	            	    {
            	            	        EOL2 = (pANTLR3_COMMON_TOKEN) MATCHT(EOL, &FOLLOW_EOL_in_actions39);
            	            	        if  (HASEXCEPTION())
            	            	        {
            	            	            goto ruleactionsEx;
            	            	        }

            	            	        EOL2_tree = (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, EOL2));
            	            	        ADAPTOR->addChild(ADAPTOR, root_0, EOL2_tree);


            	            	    }
            	            	    break;

            	            	default:
            	            	    goto loop1;	/* break out of the loop */
            	            	    break;
            	                }
            	            }
            	            loop1: ; /* Jump out to here if this rule does not match */


            	        }
            	        break;

            	    default:

            		if ( cnt2 >= 1 )
            		{
            		    goto loop2;
            		}
            		/* mismatchedSetEx()
            		 */
            		CONSTRUCTEX();
            		EXCEPTION->type = ANTLR3_EARLY_EXIT_EXCEPTION;
            		EXCEPTION->name = (void *)ANTLR3_EARLY_EXIT_NAME;


            		goto ruleactionsEx;
            	}
            	cnt2++;
                }
                loop2: ;	/* Jump to here if this rule does not match */
            }

        }

    }

    // This is where rules clean up and exit
    //
    goto ruleactionsEx; /* Prevent compiler warnings */
    ruleactionsEx: ;
    retval.stop = LT(-1);


    	retval.stop = LT(-1);

    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }
    return retval;
}
/* $ANTLR end actions */

/**
 * $ANTLR start state_description
 * /Users/Robert/src/MiPal/GUNao/posix/gufsm/qfsm2gu/../LANGUAGE/ActionsContainer.g:11:1: state_description : state_id state_name EOL description -> ^( state_id ^( STATENAME ( state_name )* ) description ) ;
 */
static ActionsContainerParser_state_description_return
state_description(pActionsContainerParser ctx)
{
    ActionsContainerParser_state_description_return retval;


    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    EOL5;
    ActionsContainerParser_state_id_return state_id3;
    #undef	RETURN_TYPE_state_id3
    #define	RETURN_TYPE_state_id3 ActionsContainerParser_state_id_return

    ActionsContainerParser_state_name_return state_name4;
    #undef	RETURN_TYPE_state_name4
    #define	RETURN_TYPE_state_name4 ActionsContainerParser_state_name_return

    ActionsContainerParser_description_return description6;
    #undef	RETURN_TYPE_description6
    #define	RETURN_TYPE_description6 ActionsContainerParser_description_return

    pANTLR3_BASE_TREE EOL5_tree;
    pANTLR3_REWRITE_RULE_TOKEN_STREAM stream_EOL;
    pANTLR3_REWRITE_RULE_SUBTREE_STREAM stream_state_id;
    pANTLR3_REWRITE_RULE_SUBTREE_STREAM stream_description;
    pANTLR3_REWRITE_RULE_SUBTREE_STREAM stream_state_name;
    /* Initialize rule variables
     */

    root_0 = NULL;

    EOL5       = NULL;
    state_id3.tree = NULL;

    state_name4.tree = NULL;

    description6.tree = NULL;
    retval.start = LT(1); retval.stop = retval.start;


    EOL5_tree   = NULL;

    stream_EOL   = NULL;
    #define CREATE_stream_EOL  if (stream_EOL == NULL) {stream_EOL = antlr3RewriteRuleTOKENStreamNewAE(ADAPTOR, RECOGNIZER, (pANTLR3_UINT8)"token EOL"); } 
    stream_state_id   = NULL;
    #define CREATE_stream_state_id  if (stream_state_id == NULL) {stream_state_id = antlr3RewriteRuleSubtreeStreamNewAE(ADAPTOR, RECOGNIZER, (pANTLR3_UINT8)"rule state_id"); }
    stream_description   = NULL;
    #define CREATE_stream_description  if (stream_description == NULL) {stream_description = antlr3RewriteRuleSubtreeStreamNewAE(ADAPTOR, RECOGNIZER, (pANTLR3_UINT8)"rule description"); }
    stream_state_name   = NULL;
    #define CREATE_stream_state_name  if (stream_state_name == NULL) {stream_state_name = antlr3RewriteRuleSubtreeStreamNewAE(ADAPTOR, RECOGNIZER, (pANTLR3_UINT8)"rule state_name"); }

    retval.tree  = NULL;

    {
        // /Users/Robert/src/MiPal/GUNao/posix/gufsm/qfsm2gu/../LANGUAGE/ActionsContainer.g:11:19: ( state_id state_name EOL description -> ^( state_id ^( STATENAME ( state_name )* ) description ) )
        // /Users/Robert/src/MiPal/GUNao/posix/gufsm/qfsm2gu/../LANGUAGE/ActionsContainer.g:11:21: state_id state_name EOL description
        {
            FOLLOWPUSH(FOLLOW_state_id_in_state_description52);
            state_id3=state_id(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto rulestate_descriptionEx;
            }

            CREATE_stream_state_id; stream_state_id->add(stream_state_id, state_id3.tree, NULL);

            FOLLOWPUSH(FOLLOW_state_name_in_state_description54);
            state_name4=state_name(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto rulestate_descriptionEx;
            }

            CREATE_stream_state_name; stream_state_name->add(stream_state_name, state_name4.tree, NULL);

            EOL5 = (pANTLR3_COMMON_TOKEN) MATCHT(EOL, &FOLLOW_EOL_in_state_description56);
            if  (HASEXCEPTION())
            {
                goto rulestate_descriptionEx;
            }
             
            CREATE_stream_EOL; stream_EOL->add(stream_EOL, EOL5, NULL);


            FOLLOWPUSH(FOLLOW_description_in_state_description58);
            description6=description(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto rulestate_descriptionEx;
            }

            CREATE_stream_description; stream_description->add(stream_description, description6.tree, NULL);

            /* AST REWRITE
             * elements          : state_name, description, state_id
             * token labels      : 
             * rule labels       : retval
             * token list labels : 
             * rule list labels  : 
             */
            {
            	pANTLR3_REWRITE_RULE_SUBTREE_STREAM stream_retval;

            	stream_retval=antlr3RewriteRuleSubtreeStreamNewAEE(ADAPTOR,  RECOGNIZER, (pANTLR3_UINT8)"token retval", retval.tree != NULL ? retval.tree : NULL);

            	root_0			    = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));
            	retval.tree    = root_0;
            	// 12:2: -> ^( state_id ^( STATENAME ( state_name )* ) description )
            	{
            	    // /Users/Robert/src/MiPal/GUNao/posix/gufsm/qfsm2gu/../LANGUAGE/ActionsContainer.g:12:5: ^( state_id ^( STATENAME ( state_name )* ) description )
            	    {
            	        pANTLR3_BASE_TREE root_1 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));
            	        root_1 = (pANTLR3_BASE_TREE)(ADAPTOR->becomeRoot(ADAPTOR, stream_state_id == NULL ? NULL : stream_state_id->nextNode(stream_state_id), root_1));

            	        // /Users/Robert/src/MiPal/GUNao/posix/gufsm/qfsm2gu/../LANGUAGE/ActionsContainer.g:12:17: ^( STATENAME ( state_name )* )
            	        {
            	            pANTLR3_BASE_TREE root_2 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));
            	            root_2 = (pANTLR3_BASE_TREE)(ADAPTOR->becomeRoot(ADAPTOR, 
            	            (pANTLR3_BASE_TREE)ADAPTOR->createTypeText(ADAPTOR, STATENAME, (pANTLR3_UINT8)"STATENAME")
            	            , root_2));

            	            // /Users/Robert/src/MiPal/GUNao/posix/gufsm/qfsm2gu/../LANGUAGE/ActionsContainer.g:12:30: ( state_name )*
            	            {
            	            	while ( (stream_state_name != NULL && stream_state_name->hasNext(stream_state_name))  )
            	            	{
            	            		ADAPTOR->addChild(ADAPTOR, root_2, stream_state_name == NULL ? NULL : stream_state_name->nextTree(stream_state_name));

            	            	}
            	            	if (stream_state_name != NULL) stream_state_name->reset(stream_state_name);

            	            }

            	            ADAPTOR->addChild(ADAPTOR, root_1, root_2);
            	        }

            	        ADAPTOR->addChild(ADAPTOR, root_1, stream_description == NULL ? NULL : stream_description->nextTree(stream_description));

            	        ADAPTOR->addChild(ADAPTOR, root_0, root_1);
            	    }

            	}


            	retval.tree = root_0; // set result root
            	if (stream_retval != NULL) stream_retval->free(stream_retval);


            }
        }

    }

    // This is where rules clean up and exit
    //
    goto rulestate_descriptionEx; /* Prevent compiler warnings */
    rulestate_descriptionEx: ;
    retval.stop = LT(-1);


    	retval.stop = LT(-1);

    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);
        if (stream_EOL != NULL) stream_EOL->free(stream_EOL);
        if (stream_state_id != NULL) stream_state_id->free(stream_state_id);
        if (stream_description != NULL) stream_description->free(stream_description);
        if (stream_state_name != NULL) stream_state_name->free(stream_state_name);

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }
    return retval;
}
/* $ANTLR end state_description */

/**
 * $ANTLR start description
 * /Users/Robert/src/MiPal/GUNao/posix/gufsm/qfsm2gu/../LANGUAGE/ActionsContainer.g:14:1: description : onEntry_part onExit_part internal_part ;
 */
static ActionsContainerParser_description_return
description(pActionsContainerParser ctx)
{
    ActionsContainerParser_description_return retval;


    pANTLR3_BASE_TREE root_0;

    ActionsContainerParser_onEntry_part_return onEntry_part7;
    #undef	RETURN_TYPE_onEntry_part7
    #define	RETURN_TYPE_onEntry_part7 ActionsContainerParser_onEntry_part_return

    ActionsContainerParser_onExit_part_return onExit_part8;
    #undef	RETURN_TYPE_onExit_part8
    #define	RETURN_TYPE_onExit_part8 ActionsContainerParser_onExit_part_return

    ActionsContainerParser_internal_part_return internal_part9;
    #undef	RETURN_TYPE_internal_part9
    #define	RETURN_TYPE_internal_part9 ActionsContainerParser_internal_part_return


    /* Initialize rule variables
     */

    root_0 = NULL;

    onEntry_part7.tree = NULL;

    onExit_part8.tree = NULL;

    internal_part9.tree = NULL;
    retval.start = LT(1); retval.stop = retval.start;




    retval.tree  = NULL;

    {
        // /Users/Robert/src/MiPal/GUNao/posix/gufsm/qfsm2gu/../LANGUAGE/ActionsContainer.g:14:12: ( onEntry_part onExit_part internal_part )
        // /Users/Robert/src/MiPal/GUNao/posix/gufsm/qfsm2gu/../LANGUAGE/ActionsContainer.g:14:14: onEntry_part onExit_part internal_part
        {
            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));


            FOLLOWPUSH(FOLLOW_onEntry_part_in_description90);
            onEntry_part7=onEntry_part(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto ruledescriptionEx;
            }

            ADAPTOR->addChild(ADAPTOR, root_0, onEntry_part7.tree);

            FOLLOWPUSH(FOLLOW_onExit_part_in_description92);
            onExit_part8=onExit_part(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto ruledescriptionEx;
            }

            ADAPTOR->addChild(ADAPTOR, root_0, onExit_part8.tree);

            FOLLOWPUSH(FOLLOW_internal_part_in_description94);
            internal_part9=internal_part(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto ruledescriptionEx;
            }

            ADAPTOR->addChild(ADAPTOR, root_0, internal_part9.tree);

        }

    }

    // This is where rules clean up and exit
    //
    goto ruledescriptionEx; /* Prevent compiler warnings */
    ruledescriptionEx: ;
    retval.stop = LT(-1);


    	retval.stop = LT(-1);

    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }
    return retval;
}
/* $ANTLR end description */

/**
 * $ANTLR start onEntry_part
 * /Users/Robert/src/MiPal/GUNao/posix/gufsm/qfsm2gu/../LANGUAGE/ActionsContainer.g:16:1: onEntry_part : ONENTRY ^ block EOL ;
 */
static ActionsContainerParser_onEntry_part_return
onEntry_part(pActionsContainerParser ctx)
{
    ActionsContainerParser_onEntry_part_return retval;


    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    ONENTRY10;
    pANTLR3_COMMON_TOKEN    EOL12;
    ActionsContainer_SimpleCParser_block_return block11;
    #undef	RETURN_TYPE_block11
    #define	RETURN_TYPE_block11 ActionsContainer_SimpleCParser_block_return

    pANTLR3_BASE_TREE ONENTRY10_tree;
    pANTLR3_BASE_TREE EOL12_tree;

    /* Initialize rule variables
     */

    root_0 = NULL;

    ONENTRY10       = NULL;
    EOL12       = NULL;
    block11.tree = NULL;
    retval.start = LT(1); retval.stop = retval.start;


    ONENTRY10_tree   = NULL;
    EOL12_tree   = NULL;


    retval.tree  = NULL;

    {
        // /Users/Robert/src/MiPal/GUNao/posix/gufsm/qfsm2gu/../LANGUAGE/ActionsContainer.g:16:13: ( ONENTRY ^ block EOL )
        // /Users/Robert/src/MiPal/GUNao/posix/gufsm/qfsm2gu/../LANGUAGE/ActionsContainer.g:16:16: ONENTRY ^ block EOL
        {
            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));


            ONENTRY10 = (pANTLR3_COMMON_TOKEN) MATCHT(ONENTRY, &FOLLOW_ONENTRY_in_onEntry_part103);
            if  (HASEXCEPTION())
            {
                goto ruleonEntry_partEx;
            }

            ONENTRY10_tree = 
            (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, ONENTRY10))
            ;
            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->becomeRoot(ADAPTOR, ONENTRY10_tree, root_0));


            FOLLOWPUSH(FOLLOW_block_in_onEntry_part106);
            block11=block(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto ruleonEntry_partEx;
            }

            ADAPTOR->addChild(ADAPTOR, root_0, block11.tree);

            EOL12 = (pANTLR3_COMMON_TOKEN) MATCHT(EOL, &FOLLOW_EOL_in_onEntry_part108);
            if  (HASEXCEPTION())
            {
                goto ruleonEntry_partEx;
            }

            EOL12_tree = (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, EOL12));
            ADAPTOR->addChild(ADAPTOR, root_0, EOL12_tree);


        }

    }

    // This is where rules clean up and exit
    //
    goto ruleonEntry_partEx; /* Prevent compiler warnings */
    ruleonEntry_partEx: ;
    retval.stop = LT(-1);


    	retval.stop = LT(-1);

    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }
    return retval;
}
/* $ANTLR end onEntry_part */

/**
 * $ANTLR start onExit_part
 * /Users/Robert/src/MiPal/GUNao/posix/gufsm/qfsm2gu/../LANGUAGE/ActionsContainer.g:18:1: onExit_part : ONEXIT ^ block EOL ;
 */
static ActionsContainerParser_onExit_part_return
onExit_part(pActionsContainerParser ctx)
{
    ActionsContainerParser_onExit_part_return retval;


    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    ONEXIT13;
    pANTLR3_COMMON_TOKEN    EOL15;
    ActionsContainer_SimpleCParser_block_return block14;
    #undef	RETURN_TYPE_block14
    #define	RETURN_TYPE_block14 ActionsContainer_SimpleCParser_block_return

    pANTLR3_BASE_TREE ONEXIT13_tree;
    pANTLR3_BASE_TREE EOL15_tree;

    /* Initialize rule variables
     */

    root_0 = NULL;

    ONEXIT13       = NULL;
    EOL15       = NULL;
    block14.tree = NULL;
    retval.start = LT(1); retval.stop = retval.start;


    ONEXIT13_tree   = NULL;
    EOL15_tree   = NULL;


    retval.tree  = NULL;

    {
        // /Users/Robert/src/MiPal/GUNao/posix/gufsm/qfsm2gu/../LANGUAGE/ActionsContainer.g:18:12: ( ONEXIT ^ block EOL )
        // /Users/Robert/src/MiPal/GUNao/posix/gufsm/qfsm2gu/../LANGUAGE/ActionsContainer.g:18:15: ONEXIT ^ block EOL
        {
            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));


            ONEXIT13 = (pANTLR3_COMMON_TOKEN) MATCHT(ONEXIT, &FOLLOW_ONEXIT_in_onExit_part118);
            if  (HASEXCEPTION())
            {
                goto ruleonExit_partEx;
            }

            ONEXIT13_tree = 
            (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, ONEXIT13))
            ;
            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->becomeRoot(ADAPTOR, ONEXIT13_tree, root_0));


            FOLLOWPUSH(FOLLOW_block_in_onExit_part121);
            block14=block(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto ruleonExit_partEx;
            }

            ADAPTOR->addChild(ADAPTOR, root_0, block14.tree);

            EOL15 = (pANTLR3_COMMON_TOKEN) MATCHT(EOL, &FOLLOW_EOL_in_onExit_part123);
            if  (HASEXCEPTION())
            {
                goto ruleonExit_partEx;
            }

            EOL15_tree = (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, EOL15));
            ADAPTOR->addChild(ADAPTOR, root_0, EOL15_tree);


        }

    }

    // This is where rules clean up and exit
    //
    goto ruleonExit_partEx; /* Prevent compiler warnings */
    ruleonExit_partEx: ;
    retval.stop = LT(-1);


    	retval.stop = LT(-1);

    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }
    return retval;
}
/* $ANTLR end onExit_part */

/**
 * $ANTLR start internal_part
 * /Users/Robert/src/MiPal/GUNao/posix/gufsm/qfsm2gu/../LANGUAGE/ActionsContainer.g:20:1: internal_part : block -> ^( INTERNALPART block ) ;
 */
static ActionsContainerParser_internal_part_return
internal_part(pActionsContainerParser ctx)
{
    ActionsContainerParser_internal_part_return retval;


    pANTLR3_BASE_TREE root_0;

    ActionsContainer_SimpleCParser_block_return block16;
    #undef	RETURN_TYPE_block16
    #define	RETURN_TYPE_block16 ActionsContainer_SimpleCParser_block_return

    pANTLR3_REWRITE_RULE_SUBTREE_STREAM stream_block;
    /* Initialize rule variables
     */

    root_0 = NULL;

    block16.tree = NULL;
    retval.start = LT(1); retval.stop = retval.start;



    stream_block   = NULL;
    #define CREATE_stream_block  if (stream_block == NULL) {stream_block = antlr3RewriteRuleSubtreeStreamNewAE(ADAPTOR, RECOGNIZER, (pANTLR3_UINT8)"rule block"); }

    retval.tree  = NULL;

    {
        // /Users/Robert/src/MiPal/GUNao/posix/gufsm/qfsm2gu/../LANGUAGE/ActionsContainer.g:20:14: ( block -> ^( INTERNALPART block ) )
        // /Users/Robert/src/MiPal/GUNao/posix/gufsm/qfsm2gu/../LANGUAGE/ActionsContainer.g:20:16: block
        {
            FOLLOWPUSH(FOLLOW_block_in_internal_part132);
            block16=block(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto ruleinternal_partEx;
            }

            CREATE_stream_block; stream_block->add(stream_block, block16.tree, NULL);

            /* AST REWRITE
             * elements          : block
             * token labels      : 
             * rule labels       : retval
             * token list labels : 
             * rule list labels  : 
             */
            {
            	pANTLR3_REWRITE_RULE_SUBTREE_STREAM stream_retval;

            	stream_retval=antlr3RewriteRuleSubtreeStreamNewAEE(ADAPTOR,  RECOGNIZER, (pANTLR3_UINT8)"token retval", retval.tree != NULL ? retval.tree : NULL);

            	root_0			    = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));
            	retval.tree    = root_0;
            	// 20:22: -> ^( INTERNALPART block )
            	{
            	    // /Users/Robert/src/MiPal/GUNao/posix/gufsm/qfsm2gu/../LANGUAGE/ActionsContainer.g:20:25: ^( INTERNALPART block )
            	    {
            	        pANTLR3_BASE_TREE root_1 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));
            	        root_1 = (pANTLR3_BASE_TREE)(ADAPTOR->becomeRoot(ADAPTOR, 
            	        (pANTLR3_BASE_TREE)ADAPTOR->createTypeText(ADAPTOR, INTERNALPART, (pANTLR3_UINT8)"INTERNALPART")
            	        , root_1));

            	        ADAPTOR->addChild(ADAPTOR, root_1, stream_block == NULL ? NULL : stream_block->nextTree(stream_block));

            	        ADAPTOR->addChild(ADAPTOR, root_0, root_1);
            	    }

            	}


            	retval.tree = root_0; // set result root
            	if (stream_retval != NULL) stream_retval->free(stream_retval);


            }
        }

    }

    // This is where rules clean up and exit
    //
    goto ruleinternal_partEx; /* Prevent compiler warnings */
    ruleinternal_partEx: ;
    retval.stop = LT(-1);


    	retval.stop = LT(-1);

    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);
        if (stream_block != NULL) stream_block->free(stream_block);

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }
    return retval;
}
/* $ANTLR end internal_part */

/**
 * $ANTLR start state_name
 * /Users/Robert/src/MiPal/GUNao/posix/gufsm/qfsm2gu/../LANGUAGE/ActionsContainer.g:22:1: state_name : K_ID ;
 */
static ActionsContainerParser_state_name_return
state_name(pActionsContainerParser ctx)
{
    ActionsContainerParser_state_name_return retval;


    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    K_ID17;

    pANTLR3_BASE_TREE K_ID17_tree;

    /* Initialize rule variables
     */

    root_0 = NULL;

    K_ID17       = NULL;
    retval.start = LT(1); retval.stop = retval.start;


    K_ID17_tree   = NULL;


    retval.tree  = NULL;

    {
        // /Users/Robert/src/MiPal/GUNao/posix/gufsm/qfsm2gu/../LANGUAGE/ActionsContainer.g:22:11: ( K_ID )
        // /Users/Robert/src/MiPal/GUNao/posix/gufsm/qfsm2gu/../LANGUAGE/ActionsContainer.g:22:14: K_ID
        {
            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));


            K_ID17 = (pANTLR3_COMMON_TOKEN) MATCHT(K_ID, &FOLLOW_K_ID_in_state_name151);
            if  (HASEXCEPTION())
            {
                goto rulestate_nameEx;
            }

            K_ID17_tree = (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, K_ID17));
            ADAPTOR->addChild(ADAPTOR, root_0, K_ID17_tree);


        }

    }

    // This is where rules clean up and exit
    //
    goto rulestate_nameEx; /* Prevent compiler warnings */
    rulestate_nameEx: ;
    retval.stop = LT(-1);


    	retval.stop = LT(-1);

    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }
    return retval;
}
/* $ANTLR end state_name */

/**
 * $ANTLR start state_id
 * /Users/Robert/src/MiPal/GUNao/posix/gufsm/qfsm2gu/../LANGUAGE/ActionsContainer.g:24:1: state_id : K_INT ;
 */
static ActionsContainerParser_state_id_return
state_id(pActionsContainerParser ctx)
{
    ActionsContainerParser_state_id_return retval;


    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    K_INT18;

    pANTLR3_BASE_TREE K_INT18_tree;

    /* Initialize rule variables
     */

    root_0 = NULL;

    K_INT18       = NULL;
    retval.start = LT(1); retval.stop = retval.start;


    K_INT18_tree   = NULL;


    retval.tree  = NULL;

    {
        // /Users/Robert/src/MiPal/GUNao/posix/gufsm/qfsm2gu/../LANGUAGE/ActionsContainer.g:24:9: ( K_INT )
        // /Users/Robert/src/MiPal/GUNao/posix/gufsm/qfsm2gu/../LANGUAGE/ActionsContainer.g:24:12: K_INT
        {
            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));


            K_INT18 = (pANTLR3_COMMON_TOKEN) MATCHT(K_INT, &FOLLOW_K_INT_in_state_id159);
            if  (HASEXCEPTION())
            {
                goto rulestate_idEx;
            }

            K_INT18_tree = (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, K_INT18));
            ADAPTOR->addChild(ADAPTOR, root_0, K_INT18_tree);


        }

    }

    // This is where rules clean up and exit
    //
    goto rulestate_idEx; /* Prevent compiler warnings */
    rulestate_idEx: ;
    retval.stop = LT(-1);


    	retval.stop = LT(-1);

    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }
    return retval;
}
/* $ANTLR end state_id */
	// Delegated methods that appear to be a part of this
	// parser
	//
    ActionsContainer_SimpleCParser_forStat_return forStat(pActionsContainerParser ctx)
    {
        return        ctx->gSimpleCParser->forStat(ctx->gSimpleCParser);
	}

    ActionsContainer_SimpleCParser_declaration_return declaration(pActionsContainerParser ctx)
    {
        return        ctx->gSimpleCParser->declaration(ctx->gSimpleCParser);
	}

    ActionsContainer_SimpleCParser_formalParameter_return formalParameter(pActionsContainerParser ctx)
    {
        return        ctx->gSimpleCParser->formalParameter(ctx->gSimpleCParser);
	}

    ActionsContainer_SimpleCParser_statement_return statement(pActionsContainerParser ctx)
    {
        return        ctx->gSimpleCParser->statement(ctx->gSimpleCParser);
	}

    ActionsContainer_SimpleCParser_functionHeader_return functionHeader(pActionsContainerParser ctx)
    {
        return        ctx->gSimpleCParser->functionHeader(ctx->gSimpleCParser);
	}

    ActionsContainer_SimpleCParser_expr_return expr(pActionsContainerParser ctx)
    {
        return        ctx->gSimpleCParser->expr(ctx->gSimpleCParser);
	}

    ActionsContainer_SimpleCParser_declarator_return declarator(pActionsContainerParser ctx)
    {
        return        ctx->gSimpleCParser->declarator(ctx->gSimpleCParser);
	}

    ActionsContainer_SimpleCParser_condExpr_return condExpr(pActionsContainerParser ctx)
    {
        return        ctx->gSimpleCParser->condExpr(ctx->gSimpleCParser);
	}

    ActionsContainer_SimpleCParser_aexpr_return aexpr(pActionsContainerParser ctx)
    {
        return        ctx->gSimpleCParser->aexpr(ctx->gSimpleCParser);
	}

    ActionsContainer_SimpleCParser_functionCallOrVariable_return functionCallOrVariable(pActionsContainerParser ctx)
    {
        return        ctx->gSimpleCParser->functionCallOrVariable(ctx->gSimpleCParser);
	}

    ActionsContainer_SimpleCParser_literal_return literal(pActionsContainerParser ctx)
    {
        return        ctx->gSimpleCParser->literal(ctx->gSimpleCParser);
	}

    ActionsContainer_SimpleCParser_program_return program(pActionsContainerParser ctx)
    {
        return        ctx->gSimpleCParser->program(ctx->gSimpleCParser);
	}

    ActionsContainer_SimpleCParser_assignStat_return assignStat(pActionsContainerParser ctx)
    {
        return        ctx->gSimpleCParser->assignStat(ctx->gSimpleCParser);
	}

    ActionsContainer_SimpleCParser_atom_return atom(pActionsContainerParser ctx)
    {
        return        ctx->gSimpleCParser->atom(ctx->gSimpleCParser);
	}

    ActionsContainer_SimpleCParser_variable_return variable(pActionsContainerParser ctx)
    {
        return        ctx->gSimpleCParser->variable(ctx->gSimpleCParser);
	}

    ActionsContainer_SimpleCParser_block_return block(pActionsContainerParser ctx)
    {
        return        ctx->gSimpleCParser->block(ctx->gSimpleCParser);
	}

    ActionsContainer_SimpleCParser_type_return type(pActionsContainerParser ctx)
    {
        return        ctx->gSimpleCParser->type(ctx->gSimpleCParser);
	}

/* End of parsing rules
 * ==============================================
 */

/* ==============================================
 * Syntactic predicates
 */
/* End of syntactic predicates
 * ==============================================
 */






/* End of code
 * =============================================================================
 */
