/** \file
 *  This C source file was generated by $ANTLR version 3.4
 *
 *     -  From the grammar source file : /Users/Robert/src/MiPal/GUNao/posix/gufsm/qfsm2gu/../LANGUAGE/SimpleCLexer.g
 *     -                            On : 2011-12-15 13:57:49
 *     -                 for the lexer : SimpleCLexerLexer
 *
 * Editing it, at least manually, is not wise.
 *
 * C language generator and runtime by Jim Idle, jimi|hereisanat|idle|dotgoeshere|ws.
 *
 *
*/
// [The "BSD license"]
// Copyright (c) 2005-2009 Jim Idle, Temporal Wave LLC
// http://www.temporal-wave.com
// http://www.linkedin.com/in/jimidle
//
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
// 1. Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
// 2. Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
// 3. The name of the author may not be used to endorse or promote products
//    derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
// IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
// OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
// INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
// NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
// THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

/* -----------------------------------------
 * Include the ANTLR3 generated header file.
 */
#include    "SimpleCLexer.h"
/* ----------------------------------------- */


/** String literals used by SimpleCLexer that we must do things like MATCHS() with.
 *  C will normally just lay down 8 bit characters, and you can use L"xxx" to
 *  get wchar_t, but wchar_t is 16 bits on Windows, which is not UTF32 and so
 *  we perform this little trick of defining the literals as arrays of UINT32
 *  and passing in the address of these.
 */
static ANTLR3_UCHAR	lit_1[]  = { 0x4F, 0x6E, 0x45, 0x6E, 0x74, 0x72, 0x79,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_2[]  = { 0x4F, 0x6E, 0x45, 0x78, 0x69, 0x74,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_3[]  = { 0x66, 0x6F, 0x72,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_4[]  = { 0x63, 0x68, 0x61, 0x72,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_5[]  = { 0x69, 0x6E, 0x74,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_6[]  = { 0x76, 0x6F, 0x69, 0x64,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_7[]  = { 0x3D, 0x3D,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_8[]  = { 0x26, 0x26,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_9[]  = { 0x7C, 0x7C,  ANTLR3_STRING_TERMINATOR};





/* MACROS that hide the C interface implementations from the
 * generated code, which makes it a little more understandable to the human eye.
 * I am very much against using C pre-processor macros for function calls and bits
 * of code as you cannot see what is happening when single stepping in debuggers
 * and so on. The exception (in my book at least) is for generated code, where you are
 * not maintaining it, but may wish to read and understand it. If you single step it, you know that input()
 * hides some indirect calls, but is always referring to the input stream. This is
 * probably more readable than ctx->input->istream->input(snarfle0->blarg) and allows me to rejig
 * the runtime interfaces without changing the generated code too often, without
 * confusing the reader of the generated output, who may not wish to know the gory
 * details of the interface inheritance.
 */

#define		CTX	ctx

/* Aids in accessing scopes for grammar programmers
 */
#undef	SCOPE_TYPE
#undef	SCOPE_STACK
#undef	SCOPE_TOP
#define	SCOPE_TYPE(scope)   pSimpleCLexer_##scope##_SCOPE
#define SCOPE_STACK(scope)  pSimpleCLexer_##scope##Stack
#define	SCOPE_TOP(scope)    ctx->pSimpleCLexer_##scope##Top
#define	SCOPE_SIZE(scope)		ctx->pSimpleCLexer_##scope##Stack_limit
#define SCOPE_INSTANCE(scope, i)	(ctx->SCOPE_STACK(scope)->get(ctx->SCOPE_STACK(scope),i))


/* Macros for accessing things in a lexer
 */
#undef	    LEXER
#undef	    RECOGNIZER
#undef	    RULEMEMO
#undef	    GETCHARINDEX
#undef	    GETLINE
#undef	    GETCHARPOSITIONINLINE
#undef	    EMIT
#undef	    EMITNEW
#undef	    MATCHC
#undef	    MATCHS
#undef	    MATCHRANGE
#undef	    LTOKEN
#undef	    HASFAILED
#undef	    FAILEDFLAG
#undef	    INPUT
#undef	    STRSTREAM
#undef	    LA
#undef	    HASEXCEPTION
#undef	    EXCEPTION
#undef	    CONSTRUCTEX
#undef	    CONSUME
#undef	    LRECOVER
#undef	    MARK
#undef	    REWIND
#undef	    REWINDLAST
#undef	    BACKTRACKING
#undef		MATCHANY
#undef		MEMOIZE
#undef		HAVEPARSEDRULE
#undef		GETTEXT
#undef		INDEX
#undef		SEEK
#undef		PUSHSTREAM
#undef		POPSTREAM
#undef		SETTEXT
#undef		SETTEXT8

#define	    LEXER					ctx->pLexer
#define	    RECOGNIZER			    LEXER->rec
#define		LEXSTATE				RECOGNIZER->state
#define		TOKSOURCE				LEXSTATE->tokSource
#define	    GETCHARINDEX()			LEXER->getCharIndex(LEXER)
#define	    GETLINE()				LEXER->getLine(LEXER)
#define	    GETTEXT()				LEXER->getText(LEXER)
#define	    GETCHARPOSITIONINLINE() LEXER->getCharPositionInLine(LEXER)
#define	    EMIT()					LEXSTATE->type = _type; LEXER->emit(LEXER)
#define	    EMITNEW(t)				LEXER->emitNew(LEXER, t)
#define	    MATCHC(c)				LEXER->matchc(LEXER, c)
#define	    MATCHS(s)				LEXER->matchs(LEXER, s)
#define	    MATCHRANGE(c1,c2)	    LEXER->matchRange(LEXER, c1, c2)
#define	    MATCHANY()				LEXER->matchAny(LEXER)
#define	    LTOKEN  				LEXSTATE->token
#define	    HASFAILED()				(LEXSTATE->failed == ANTLR3_TRUE)
#define	    BACKTRACKING			LEXSTATE->backtracking
#define	    FAILEDFLAG				LEXSTATE->failed
#define	    INPUT					LEXER->input
#define	    STRSTREAM				INPUT
#define		ISTREAM					INPUT->istream
#define		INDEX()					ISTREAM->index(ISTREAM)
#define		SEEK(n)					ISTREAM->seek(ISTREAM, n)
#define	    EOF_TOKEN				&(LEXSTATE->tokSource->eofToken)
#define	    HASEXCEPTION()			(LEXSTATE->error == ANTLR3_TRUE)
#define	    EXCEPTION				LEXSTATE->exception
#define	    CONSTRUCTEX()			RECOGNIZER->exConstruct(RECOGNIZER)
#define	    LRECOVER()				LEXER->recover(LEXER)
#define	    MARK()					ISTREAM->mark(ISTREAM)
#define	    REWIND(m)				ISTREAM->rewind(ISTREAM, m)
#define	    REWINDLAST()			ISTREAM->rewindLast(ISTREAM)
#define		MEMOIZE(ri,si)			RECOGNIZER->memoize(RECOGNIZER, ri, si)
#define		HAVEPARSEDRULE(r)		RECOGNIZER->alreadyParsedRule(RECOGNIZER, r)
#define		PUSHSTREAM(str)			LEXER->pushCharStream(LEXER, str)
#define		POPSTREAM()				LEXER->popCharStream(LEXER)
#define		SETTEXT(str)			LEXSTATE->text = str
#define		SKIP()					LEXSTATE->token = &(TOKSOURCE->skipToken)
#define		USER1					LEXSTATE->user1
#define		USER2					LEXSTATE->user2
#define		USER3					LEXSTATE->user3
#define		CUSTOM					LEXSTATE->custom
#define		RULEMEMO				LEXSTATE->ruleMemo
#define		DBG						RECOGNIZER->debugger

/* If we have been told we can rely on the standard 8 bit or UTF16 input
 * stream, then we can define our macros to use the direct pointers
 * in the input object, which is much faster than indirect calls. This
 * is really only significant to lexers with a lot of fragment rules (which
 * do not place LA(1) in a temporary at the moment) and even then
 * only if there is a lot of input (order of say 1M or so).
 */
#if	defined(ANTLR3_INLINE_INPUT_8BIT) || defined(ANTLR3_INLINE_INPUT_UTF16)

# ifdef	ANTLR3_INLINE_INPUT_8BIT

/* 8 bit character set */

#  define	    NEXTCHAR	((pANTLR3_UINT8)(INPUT->nextChar))
#  define	    DATAP	((pANTLR3_UINT8)(INPUT->data))

# else

#  define	    NEXTCHAR	((pANTLR3_UINT16)(INPUT->nextChar))
#  define	    DATAP	((pANTLR3_UINT16)(INPUT->data))

# endif

# define	    LA(n) ((NEXTCHAR + n) > (DATAP + INPUT->sizeBuf) ? ANTLR3_CHARSTREAM_EOF : (ANTLR3_UCHAR)(*(NEXTCHAR + n - 1)))
# define            CONSUME()                                           \
{                                                                       \
    if        (NEXTCHAR < (DATAP + INPUT->sizeBuf))                     \
    {                                                                   \
        INPUT->charPositionInLine++;                                    \
        if  ((ANTLR3_UCHAR)(*NEXTCHAR) == INPUT->newlineChar)           \
        {                                                               \
            INPUT->line++;                                              \
            INPUT->charPositionInLine        = 0;                       \
            INPUT->currentLine                = (void *)(NEXTCHAR + 1); \
        }                                                               \
        INPUT->nextChar = (void *)(NEXTCHAR + 1);                       \
    }                                                                   \
}

#else

// Pick up the input character by calling the input stream implementation.
//
#define	    CONSUME()   INPUT->istream->consume(INPUT->istream)
#define	    LA(n)       INPUT->istream->_LA(INPUT->istream, n)

#endif

#define		TOKTEXT(tok, txt)				tok, (pANTLR3_UINT8)txt

/* The 4 tokens defined below may well clash with your own #defines or token types. If so
 * then for the present you must use different names for your defines as these are hard coded
 * in the code generator. It would be better not to use such names internally, and maybe
 * we can change this in a forthcoming release. I deliberately do not #undef these
 * here as this will at least give you a redefined error somewhere if they clash.
 */
#define	    UP	    ANTLR3_TOKEN_UP
#define	    DOWN    ANTLR3_TOKEN_DOWN
#define	    EOR	    ANTLR3_TOKEN_EOR
#define	    INVALID ANTLR3_TOKEN_INVALID


/* =============================================================================
 * Functions to create and destroy scopes. First come the rule scopes, followed
 * by the global declared scopes.
 */



/* ============================================================================= */

/* =============================================================================
 * Start of recognizer
 */

/* Forward declare the locally static matching functions we have generated and any predicate functions.
 */
static ANTLR3_INLINE 
 void
	mEscapeSequence    (pSimpleCLexer ctx);
static ANTLR3_INLINE 
 void
	mSTRING_LITERAL    (pSimpleCLexer ctx);
static ANTLR3_INLINE 
 void
	mSTRING_GUTS    (pSimpleCLexer ctx);
static ANTLR3_INLINE 
 void
	mEOL    (pSimpleCLexer ctx);
static ANTLR3_INLINE 
 void
	mONENTRY    (pSimpleCLexer ctx);
static ANTLR3_INLINE 
 void
	mONEXIT    (pSimpleCLexer ctx);
static ANTLR3_INLINE 
 void
	mK_FOR    (pSimpleCLexer ctx);
static ANTLR3_INLINE 
 void
	mK_CHAR    (pSimpleCLexer ctx);
static ANTLR3_INLINE 
 void
	mK_INT_TYPE    (pSimpleCLexer ctx);
static ANTLR3_INLINE 
 void
	mK_VOID    (pSimpleCLexer ctx);
static ANTLR3_INLINE 
 void
	mK_ID    (pSimpleCLexer ctx);
static ANTLR3_INLINE 
 void
	mK_INT    (pSimpleCLexer ctx);
static ANTLR3_INLINE 
 void
	mK_LCURVE    (pSimpleCLexer ctx);
static ANTLR3_INLINE 
 void
	mK_RCURVE    (pSimpleCLexer ctx);
static ANTLR3_INLINE 
 void
	mK_PLUS    (pSimpleCLexer ctx);
static ANTLR3_INLINE 
 void
	mK_MINUS    (pSimpleCLexer ctx);
static ANTLR3_INLINE 
 void
	mK_COMMA    (pSimpleCLexer ctx);
static ANTLR3_INLINE 
 void
	mK_SEMICOLON    (pSimpleCLexer ctx);
static ANTLR3_INLINE 
 void
	mK_LT    (pSimpleCLexer ctx);
static ANTLR3_INLINE 
 void
	mK_EQ    (pSimpleCLexer ctx);
static ANTLR3_INLINE 
 void
	mK_EQEQ    (pSimpleCLexer ctx);
static ANTLR3_INLINE 
 void
	mK_ANDAND    (pSimpleCLexer ctx);
static ANTLR3_INLINE 
 void
	mK_OROR    (pSimpleCLexer ctx);
static ANTLR3_INLINE 
 void
	mK_NOT    (pSimpleCLexer ctx);
static ANTLR3_INLINE 
 void
	mK_LCURLY    (pSimpleCLexer ctx);
static ANTLR3_INLINE 
 void
	mK_RCURLY    (pSimpleCLexer ctx);
static ANTLR3_INLINE 
 void
	mWS    (pSimpleCLexer ctx);
static ANTLR3_INLINE 
 void
	mTokens    (pSimpleCLexer ctx);
static void	SimpleCLexerFree(pSimpleCLexer ctx);

/* =========================================================================
 * Lexer matching rules end.
 * =========================================================================
 */



static void
SimpleCLexerFree  (pSimpleCLexer ctx)
{
    LEXER->free(LEXER);

    ANTLR3_FREE(ctx);
}

static void
SimpleCLexerReset (pSimpleCLexer ctx)
{
    RECOGNIZER->reset(RECOGNIZER);
}

/** \brief Name of the grammar file that generated this code
 */
static const char fileName[] = "/Users/Robert/src/MiPal/GUNao/posix/gufsm/qfsm2gu/../LANGUAGE/SimpleCLexer.g";

/** \brief Return the name of the grammar file that generated this code.
 */
static const char * getGrammarFileName()
{
	return fileName;
}

/** \brief Create a new lexer called SimpleCLexer
 *
 * \param[in]    instream Pointer to an initialized input stream
 * \return
 *     - Success pSimpleCLexer initialized for the lex start
 *     - Fail NULL
 */
ANTLR3_API pSimpleCLexer SimpleCLexerNew
(
pANTLR3_INPUT_STREAM
 instream)
{
	// See if we can create a new lexer with the standard constructor
	//
	return SimpleCLexerNewSSD(instream, NULL);
}

/** \brief Create a new lexer called SimpleCLexer
 *
 * \param[in]    instream Pointer to an initialized input stream
 * \param[state] state Previously created shared recognizer stat
 * \return
 *     - Success pSimpleCLexer initialized for the lex start
 *     - Fail NULL
 */
ANTLR3_API pSimpleCLexer SimpleCLexerNewSSD
(pANTLR3_INPUT_STREAM instream, pANTLR3_RECOGNIZER_SHARED_STATE state)
{
    pSimpleCLexer ctx; // Context structure we will build and return

    ctx = (pSimpleCLexer) ANTLR3_CALLOC(1, sizeof(SimpleCLexer));

    if  (ctx == NULL)
    {
        // Failed to allocate memory for lexer context
        return  NULL;
    }

    /* -------------------------------------------------------------------
     * Memory for basic structure is allocated, now to fill in
     * in base ANTLR3 structures. We initialize the function pointers
     * for the standard ANTLR3 lexer function set, but upon return
     * from here, the programmer may set the pointers to provide custom
     * implementations of each function.
     *
     * We don't use the macros defined in SimpleCLexer.h here so you can get a sense
     * of what goes where.
     */

    /* Create a base lexer, using the supplied input stream
     */
    ctx->pLexer	= antlr3LexerNewStream(ANTLR3_SIZE_HINT, instream, state);

    /* Check that we allocated the memory correctly
     */
    if	(ctx->pLexer == NULL)
    {
		ANTLR3_FREE(ctx);
		return  NULL;
    }
    /* Install the implementation of our SimpleCLexer interface
     */
    ctx->mEscapeSequence	= mEscapeSequence;
    ctx->mSTRING_LITERAL	= mSTRING_LITERAL;
    ctx->mSTRING_GUTS	= mSTRING_GUTS;
    ctx->mEOL	= mEOL;
    ctx->mONENTRY	= mONENTRY;
    ctx->mONEXIT	= mONEXIT;
    ctx->mK_FOR	= mK_FOR;
    ctx->mK_CHAR	= mK_CHAR;
    ctx->mK_INT_TYPE	= mK_INT_TYPE;
    ctx->mK_VOID	= mK_VOID;
    ctx->mK_ID	= mK_ID;
    ctx->mK_INT	= mK_INT;
    ctx->mK_LCURVE	= mK_LCURVE;
    ctx->mK_RCURVE	= mK_RCURVE;
    ctx->mK_PLUS	= mK_PLUS;
    ctx->mK_MINUS	= mK_MINUS;
    ctx->mK_COMMA	= mK_COMMA;
    ctx->mK_SEMICOLON	= mK_SEMICOLON;
    ctx->mK_LT	= mK_LT;
    ctx->mK_EQ	= mK_EQ;
    ctx->mK_EQEQ	= mK_EQEQ;
    ctx->mK_ANDAND	= mK_ANDAND;
    ctx->mK_OROR	= mK_OROR;
    ctx->mK_NOT	= mK_NOT;
    ctx->mK_LCURLY	= mK_LCURLY;
    ctx->mK_RCURLY	= mK_RCURLY;
    ctx->mWS	= mWS;
    ctx->mTokens	= mTokens;

    /** When the nextToken() call is made to this lexer's pANTLR3_TOKEN_SOURCE
     *  it will call mTokens() in this generated code, and will pass it the ctx
     * pointer of this lexer, not the context of the base lexer, so store that now.
     */
    ctx->pLexer->ctx	    = ctx;

    /**Install the token matching function
     */
    ctx->pLexer->mTokens = (void (*) (void *))(mTokens);

    ctx->getGrammarFileName	= getGrammarFileName;
    ctx->free		= SimpleCLexerFree;
    ctx->reset          = SimpleCLexerReset;


    /* Return the newly built lexer to the caller
     */
    return  ctx;
}
/* =========================================================================
 * Functions to match the lexer grammar defined tokens from the input stream
 */

//   Comes from: 16:15: ( '\\\\' ( 'b' | 't' | 'n' | 'f' | 'r' | ';' | '\\\"' | '\\'' | '\\\\' ) )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start EscapeSequence
 *
 * Looks to match the characters the constitute the token EscapeSequence
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mEscapeSequence(pSimpleCLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = EscapeSequence;


    // /Users/Robert/src/MiPal/GUNao/posix/gufsm/qfsm2gu/../LANGUAGE/SimpleCLexer.g:16:15: ( '\\\\' ( 'b' | 't' | 'n' | 'f' | 'r' | ';' | '\\\"' | '\\'' | '\\\\' ) )
    // /Users/Robert/src/MiPal/GUNao/posix/gufsm/qfsm2gu/../LANGUAGE/SimpleCLexer.g:16:19: '\\\\' ( 'b' | 't' | 'n' | 'f' | 'r' | ';' | '\\\"' | '\\'' | '\\\\' )
    {
        MATCHC('\\');
        if  (HASEXCEPTION())
        {
            goto ruleEscapeSequenceEx;
        }


        if ( LA(1) == '"' || LA(1) == '\'' || LA(1) == ';' || LA(1) == '\\' || LA(1) == 'b' || LA(1) == 'f' || LA(1) == 'n' || LA(1) == 'r' || LA(1) == 't' )
        {
            CONSUME();
        }
        else
        {
            CONSTRUCTEX();
            EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
            EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

            LRECOVER();
            goto ruleEscapeSequenceEx;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleEscapeSequenceEx; /* Prevent compiler warnings */
    ruleEscapeSequenceEx: ;

}
// $ANTLR end EscapeSequence

//   Comes from: 18:15: ( '\"' STRING_GUTS '\"' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start STRING_LITERAL
 *
 * Looks to match the characters the constitute the token STRING_LITERAL
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mSTRING_LITERAL(pSimpleCLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = STRING_LITERAL;


    // /Users/Robert/src/MiPal/GUNao/posix/gufsm/qfsm2gu/../LANGUAGE/SimpleCLexer.g:18:15: ( '\"' STRING_GUTS '\"' )
    // /Users/Robert/src/MiPal/GUNao/posix/gufsm/qfsm2gu/../LANGUAGE/SimpleCLexer.g:18:18: '\"' STRING_GUTS '\"'
    {
        MATCHC('"');
        if  (HASEXCEPTION())
        {
            goto ruleSTRING_LITERALEx;
        }


        /* 18:18: '\"' STRING_GUTS '\"' */
        mSTRING_GUTS(ctx );
        if  (HASEXCEPTION())
        {
            goto ruleSTRING_LITERALEx;
        }



        MATCHC('"');
        if  (HASEXCEPTION())
        {
            goto ruleSTRING_LITERALEx;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleSTRING_LITERALEx; /* Prevent compiler warnings */
    ruleSTRING_LITERALEx: ;

}
// $ANTLR end STRING_LITERAL

//   Comes from: 21:12: ( ( EscapeSequence |~ ( '\\\\' | '\"' ) )* )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start STRING_GUTS
 *
 * Looks to match the characters the constitute the token STRING_GUTS
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mSTRING_GUTS(pSimpleCLexer ctx)
{
	ANTLR3_UINT32	_type;


    // /Users/Robert/src/MiPal/GUNao/posix/gufsm/qfsm2gu/../LANGUAGE/SimpleCLexer.g:21:12: ( ( EscapeSequence |~ ( '\\\\' | '\"' ) )* )
    // /Users/Robert/src/MiPal/GUNao/posix/gufsm/qfsm2gu/../LANGUAGE/SimpleCLexer.g:21:14: ( EscapeSequence |~ ( '\\\\' | '\"' ) )*
    {
        // /Users/Robert/src/MiPal/GUNao/posix/gufsm/qfsm2gu/../LANGUAGE/SimpleCLexer.g:21:14: ( EscapeSequence |~ ( '\\\\' | '\"' ) )*

        for (;;)
        {
            int alt1=3;
            {
               /* dfaLoopbackState(k,edges,eotPredictsAlt,description,stateNumber,semPredState)
                */
                int LA1_0 = LA(1);
                if ( (LA1_0 == '\\'))
                {
                    alt1=1;
                }
                else if ( (((LA1_0 >= 0x0000) && (LA1_0 <= '!')) || ((LA1_0 >= '#') && (LA1_0 <= '[')) || ((LA1_0 >= ']') && (LA1_0 <= 0xFFFF))))
                {
                    alt1=2;
                }

            }
            switch (alt1)
            {
        	case 1:
        	    // /Users/Robert/src/MiPal/GUNao/posix/gufsm/qfsm2gu/../LANGUAGE/SimpleCLexer.g:21:16: EscapeSequence
        	    {
        	        /* 21:16: EscapeSequence */
        	        mEscapeSequence(ctx );
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleSTRING_GUTSEx;
        	        }



        	    }
        	    break;
        	case 2:
        	    // /Users/Robert/src/MiPal/GUNao/posix/gufsm/qfsm2gu/../LANGUAGE/SimpleCLexer.g:21:33: ~ ( '\\\\' | '\"' )
        	    {
        	        if ( ((LA(1) >= 0x0000) && (LA(1) <= '!')) || ((LA(1) >= '#') && (LA(1) <= '[')) || ((LA(1) >= ']') && (LA(1) <= 0xFFFF)) )
        	        {
        	            CONSUME();
        	        }
        	        else
        	        {
        	            CONSTRUCTEX();
        	            EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
        	            EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

        	            LRECOVER();
        	            goto ruleSTRING_GUTSEx;
        	        }


        	    }
        	    break;

        	default:
        	    goto loop1;	/* break out of the loop */
        	    break;
            }
        }
        loop1: ; /* Jump out to here if this rule does not match */


    }


    // This is where rules clean up and exit
    //
    goto ruleSTRING_GUTSEx; /* Prevent compiler warnings */
    ruleSTRING_GUTSEx: ;

}
// $ANTLR end STRING_GUTS

//   Comes from: 23:5: ( '\\n' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start EOL
 *
 * Looks to match the characters the constitute the token EOL
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mEOL(pSimpleCLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = EOL;


    // /Users/Robert/src/MiPal/GUNao/posix/gufsm/qfsm2gu/../LANGUAGE/SimpleCLexer.g:23:5: ( '\\n' )
    // /Users/Robert/src/MiPal/GUNao/posix/gufsm/qfsm2gu/../LANGUAGE/SimpleCLexer.g:23:7: '\\n'
    {
        MATCHC('\n');
        if  (HASEXCEPTION())
        {
            goto ruleEOLEx;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleEOLEx; /* Prevent compiler warnings */
    ruleEOLEx: ;

}
// $ANTLR end EOL

//   Comes from: 25:8: ( 'OnEntry' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start ONENTRY
 *
 * Looks to match the characters the constitute the token ONENTRY
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mONENTRY(pSimpleCLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = ONENTRY;


    // /Users/Robert/src/MiPal/GUNao/posix/gufsm/qfsm2gu/../LANGUAGE/SimpleCLexer.g:25:8: ( 'OnEntry' )
    // /Users/Robert/src/MiPal/GUNao/posix/gufsm/qfsm2gu/../LANGUAGE/SimpleCLexer.g:25:10: 'OnEntry'
    {
        MATCHS(lit_1);
        if  (HASEXCEPTION())
        {
            goto ruleONENTRYEx;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleONENTRYEx; /* Prevent compiler warnings */
    ruleONENTRYEx: ;

}
// $ANTLR end ONENTRY

//   Comes from: 27:7: ( 'OnExit' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start ONEXIT
 *
 * Looks to match the characters the constitute the token ONEXIT
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mONEXIT(pSimpleCLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = ONEXIT;


    // /Users/Robert/src/MiPal/GUNao/posix/gufsm/qfsm2gu/../LANGUAGE/SimpleCLexer.g:27:7: ( 'OnExit' )
    // /Users/Robert/src/MiPal/GUNao/posix/gufsm/qfsm2gu/../LANGUAGE/SimpleCLexer.g:27:10: 'OnExit'
    {
        MATCHS(lit_2);
        if  (HASEXCEPTION())
        {
            goto ruleONEXITEx;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleONEXITEx; /* Prevent compiler warnings */
    ruleONEXITEx: ;

}
// $ANTLR end ONEXIT

//   Comes from: 29:7: ( 'for' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start K_FOR
 *
 * Looks to match the characters the constitute the token K_FOR
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mK_FOR(pSimpleCLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = K_FOR;


    // /Users/Robert/src/MiPal/GUNao/posix/gufsm/qfsm2gu/../LANGUAGE/SimpleCLexer.g:29:7: ( 'for' )
    // /Users/Robert/src/MiPal/GUNao/posix/gufsm/qfsm2gu/../LANGUAGE/SimpleCLexer.g:29:9: 'for'
    {
        MATCHS(lit_3);
        if  (HASEXCEPTION())
        {
            goto ruleK_FOREx;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleK_FOREx; /* Prevent compiler warnings */
    ruleK_FOREx: ;

}
// $ANTLR end K_FOR

//   Comes from: 30:7: ( 'char' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start K_CHAR
 *
 * Looks to match the characters the constitute the token K_CHAR
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mK_CHAR(pSimpleCLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = K_CHAR;


    // /Users/Robert/src/MiPal/GUNao/posix/gufsm/qfsm2gu/../LANGUAGE/SimpleCLexer.g:30:7: ( 'char' )
    // /Users/Robert/src/MiPal/GUNao/posix/gufsm/qfsm2gu/../LANGUAGE/SimpleCLexer.g:30:9: 'char'
    {
        MATCHS(lit_4);
        if  (HASEXCEPTION())
        {
            goto ruleK_CHAREx;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleK_CHAREx; /* Prevent compiler warnings */
    ruleK_CHAREx: ;

}
// $ANTLR end K_CHAR

//   Comes from: 31:12: ( 'int' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start K_INT_TYPE
 *
 * Looks to match the characters the constitute the token K_INT_TYPE
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mK_INT_TYPE(pSimpleCLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = K_INT_TYPE;


    // /Users/Robert/src/MiPal/GUNao/posix/gufsm/qfsm2gu/../LANGUAGE/SimpleCLexer.g:31:12: ( 'int' )
    // /Users/Robert/src/MiPal/GUNao/posix/gufsm/qfsm2gu/../LANGUAGE/SimpleCLexer.g:31:14: 'int'
    {
        MATCHS(lit_5);
        if  (HASEXCEPTION())
        {
            goto ruleK_INT_TYPEEx;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleK_INT_TYPEEx; /* Prevent compiler warnings */
    ruleK_INT_TYPEEx: ;

}
// $ANTLR end K_INT_TYPE

//   Comes from: 32:7: ( 'void' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start K_VOID
 *
 * Looks to match the characters the constitute the token K_VOID
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mK_VOID(pSimpleCLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = K_VOID;


    // /Users/Robert/src/MiPal/GUNao/posix/gufsm/qfsm2gu/../LANGUAGE/SimpleCLexer.g:32:7: ( 'void' )
    // /Users/Robert/src/MiPal/GUNao/posix/gufsm/qfsm2gu/../LANGUAGE/SimpleCLexer.g:32:9: 'void'
    {
        MATCHS(lit_6);
        if  (HASEXCEPTION())
        {
            goto ruleK_VOIDEx;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleK_VOIDEx; /* Prevent compiler warnings */
    ruleK_VOIDEx: ;

}
// $ANTLR end K_VOID

//   Comes from: 34:7: ( ( 'a' .. 'z' | 'A' .. 'Z' | '_' ) ( 'a' .. 'z' | 'A' .. 'Z' | '0' .. '9' | '_' )* )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start K_ID
 *
 * Looks to match the characters the constitute the token K_ID
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mK_ID(pSimpleCLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = K_ID;


    // /Users/Robert/src/MiPal/GUNao/posix/gufsm/qfsm2gu/../LANGUAGE/SimpleCLexer.g:34:7: ( ( 'a' .. 'z' | 'A' .. 'Z' | '_' ) ( 'a' .. 'z' | 'A' .. 'Z' | '0' .. '9' | '_' )* )
    // /Users/Robert/src/MiPal/GUNao/posix/gufsm/qfsm2gu/../LANGUAGE/SimpleCLexer.g:34:11: ( 'a' .. 'z' | 'A' .. 'Z' | '_' ) ( 'a' .. 'z' | 'A' .. 'Z' | '0' .. '9' | '_' )*
    {
        if ( ((LA(1) >= 'A') && (LA(1) <= 'Z')) || LA(1) == '_' || ((LA(1) >= 'a') && (LA(1) <= 'z')) )
        {
            CONSUME();
        }
        else
        {
            CONSTRUCTEX();
            EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
            EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

            LRECOVER();
            goto ruleK_IDEx;
        }


        // /Users/Robert/src/MiPal/GUNao/posix/gufsm/qfsm2gu/../LANGUAGE/SimpleCLexer.g:34:35: ( 'a' .. 'z' | 'A' .. 'Z' | '0' .. '9' | '_' )*

        for (;;)
        {
            int alt2=2;
            switch ( LA(1) )
            {
            case '0':
            case '1':
            case '2':
            case '3':
            case '4':
            case '5':
            case '6':
            case '7':
            case '8':
            case '9':
            case 'A':
            case 'B':
            case 'C':
            case 'D':
            case 'E':
            case 'F':
            case 'G':
            case 'H':
            case 'I':
            case 'J':
            case 'K':
            case 'L':
            case 'M':
            case 'N':
            case 'O':
            case 'P':
            case 'Q':
            case 'R':
            case 'S':
            case 'T':
            case 'U':
            case 'V':
            case 'W':
            case 'X':
            case 'Y':
            case 'Z':
            case '_':
            case 'a':
            case 'b':
            case 'c':
            case 'd':
            case 'e':
            case 'f':
            case 'g':
            case 'h':
            case 'i':
            case 'j':
            case 'k':
            case 'l':
            case 'm':
            case 'n':
            case 'o':
            case 'p':
            case 'q':
            case 'r':
            case 's':
            case 't':
            case 'u':
            case 'v':
            case 'w':
            case 'x':
            case 'y':
            case 'z':
            	{
            		alt2=1;
            	}
                break;

            }

            switch (alt2)
            {
        	case 1:
        	    // /Users/Robert/src/MiPal/GUNao/posix/gufsm/qfsm2gu/../LANGUAGE/SimpleCLexer.g:
        	    {
        	        if ( ((LA(1) >= '0') && (LA(1) <= '9')) || ((LA(1) >= 'A') && (LA(1) <= 'Z')) || LA(1) == '_' || ((LA(1) >= 'a') && (LA(1) <= 'z')) )
        	        {
        	            CONSUME();
        	        }
        	        else
        	        {
        	            CONSTRUCTEX();
        	            EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
        	            EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

        	            LRECOVER();
        	            goto ruleK_IDEx;
        	        }


        	    }
        	    break;

        	default:
        	    goto loop2;	/* break out of the loop */
        	    break;
            }
        }
        loop2: ; /* Jump out to here if this rule does not match */


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleK_IDEx; /* Prevent compiler warnings */
    ruleK_IDEx: ;

}
// $ANTLR end K_ID

//   Comes from: 37:7: ( '0' | ( '1' .. '9' ) ( '0' .. '9' )* )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start K_INT
 *
 * Looks to match the characters the constitute the token K_INT
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mK_INT(pSimpleCLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = K_INT;


    {
        //  /Users/Robert/src/MiPal/GUNao/posix/gufsm/qfsm2gu/../LANGUAGE/SimpleCLexer.g:37:7: ( '0' | ( '1' .. '9' ) ( '0' .. '9' )* )

        ANTLR3_UINT32 alt4;

        alt4=2;

        switch ( LA(1) )
        {
        case '0':
        	{
        		alt4=1;
        	}
            break;
        case '1':
        case '2':
        case '3':
        case '4':
        case '5':
        case '6':
        case '7':
        case '8':
        case '9':
        	{
        		alt4=2;
        	}
            break;

        default:
            CONSTRUCTEX();
            EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
            EXCEPTION->message      = (void *)"";
            EXCEPTION->decisionNum  = 4;
            EXCEPTION->state        = 0;


            goto ruleK_INTEx;

        }

        switch (alt4)
        {
    	case 1:
    	    // /Users/Robert/src/MiPal/GUNao/posix/gufsm/qfsm2gu/../LANGUAGE/SimpleCLexer.g:37:9: '0'
    	    {
    	        MATCHC('0');
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleK_INTEx;
    	        }


    	    }
    	    break;
    	case 2:
    	    // /Users/Robert/src/MiPal/GUNao/posix/gufsm/qfsm2gu/../LANGUAGE/SimpleCLexer.g:37:15: ( '1' .. '9' ) ( '0' .. '9' )*
    	    {
    	        if ( ((LA(1) >= '1') && (LA(1) <= '9')) )
    	        {
    	            CONSUME();
    	        }
    	        else
    	        {
    	            CONSTRUCTEX();
    	            EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
    	            EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

    	            LRECOVER();
    	            goto ruleK_INTEx;
    	        }


    	        // /Users/Robert/src/MiPal/GUNao/posix/gufsm/qfsm2gu/../LANGUAGE/SimpleCLexer.g:37:26: ( '0' .. '9' )*

    	        for (;;)
    	        {
    	            int alt3=2;
    	            switch ( LA(1) )
    	            {
    	            case '0':
    	            case '1':
    	            case '2':
    	            case '3':
    	            case '4':
    	            case '5':
    	            case '6':
    	            case '7':
    	            case '8':
    	            case '9':
    	            	{
    	            		alt3=1;
    	            	}
    	                break;

    	            }

    	            switch (alt3)
    	            {
    	        	case 1:
    	        	    // /Users/Robert/src/MiPal/GUNao/posix/gufsm/qfsm2gu/../LANGUAGE/SimpleCLexer.g:
    	        	    {
    	        	        if ( ((LA(1) >= '0') && (LA(1) <= '9')) )
    	        	        {
    	        	            CONSUME();
    	        	        }
    	        	        else
    	        	        {
    	        	            CONSTRUCTEX();
    	        	            EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
    	        	            EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

    	        	            LRECOVER();
    	        	            goto ruleK_INTEx;
    	        	        }


    	        	    }
    	        	    break;

    	        	default:
    	        	    goto loop3;	/* break out of the loop */
    	        	    break;
    	            }
    	        }
    	        loop3: ; /* Jump out to here if this rule does not match */


    	    }
    	    break;

        }
    }
	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleK_INTEx; /* Prevent compiler warnings */
    ruleK_INTEx: ;

}
// $ANTLR end K_INT

//   Comes from: 40:10: ( '(' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start K_LCURVE
 *
 * Looks to match the characters the constitute the token K_LCURVE
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mK_LCURVE(pSimpleCLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = K_LCURVE;


    // /Users/Robert/src/MiPal/GUNao/posix/gufsm/qfsm2gu/../LANGUAGE/SimpleCLexer.g:40:10: ( '(' )
    // /Users/Robert/src/MiPal/GUNao/posix/gufsm/qfsm2gu/../LANGUAGE/SimpleCLexer.g:40:12: '('
    {
        MATCHC('(');
        if  (HASEXCEPTION())
        {
            goto ruleK_LCURVEEx;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleK_LCURVEEx; /* Prevent compiler warnings */
    ruleK_LCURVEEx: ;

}
// $ANTLR end K_LCURVE

//   Comes from: 41:10: ( ')' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start K_RCURVE
 *
 * Looks to match the characters the constitute the token K_RCURVE
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mK_RCURVE(pSimpleCLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = K_RCURVE;


    // /Users/Robert/src/MiPal/GUNao/posix/gufsm/qfsm2gu/../LANGUAGE/SimpleCLexer.g:41:10: ( ')' )
    // /Users/Robert/src/MiPal/GUNao/posix/gufsm/qfsm2gu/../LANGUAGE/SimpleCLexer.g:41:12: ')'
    {
        MATCHC(')');
        if  (HASEXCEPTION())
        {
            goto ruleK_RCURVEEx;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleK_RCURVEEx; /* Prevent compiler warnings */
    ruleK_RCURVEEx: ;

}
// $ANTLR end K_RCURVE

//   Comes from: 42:8: ( '+' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start K_PLUS
 *
 * Looks to match the characters the constitute the token K_PLUS
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mK_PLUS(pSimpleCLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = K_PLUS;


    // /Users/Robert/src/MiPal/GUNao/posix/gufsm/qfsm2gu/../LANGUAGE/SimpleCLexer.g:42:8: ( '+' )
    // /Users/Robert/src/MiPal/GUNao/posix/gufsm/qfsm2gu/../LANGUAGE/SimpleCLexer.g:42:10: '+'
    {
        MATCHC('+');
        if  (HASEXCEPTION())
        {
            goto ruleK_PLUSEx;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleK_PLUSEx; /* Prevent compiler warnings */
    ruleK_PLUSEx: ;

}
// $ANTLR end K_PLUS

//   Comes from: 43:9: ( '-' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start K_MINUS
 *
 * Looks to match the characters the constitute the token K_MINUS
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mK_MINUS(pSimpleCLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = K_MINUS;


    // /Users/Robert/src/MiPal/GUNao/posix/gufsm/qfsm2gu/../LANGUAGE/SimpleCLexer.g:43:9: ( '-' )
    // /Users/Robert/src/MiPal/GUNao/posix/gufsm/qfsm2gu/../LANGUAGE/SimpleCLexer.g:43:11: '-'
    {
        MATCHC('-');
        if  (HASEXCEPTION())
        {
            goto ruleK_MINUSEx;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleK_MINUSEx; /* Prevent compiler warnings */
    ruleK_MINUSEx: ;

}
// $ANTLR end K_MINUS

//   Comes from: 44:9: ( ',' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start K_COMMA
 *
 * Looks to match the characters the constitute the token K_COMMA
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mK_COMMA(pSimpleCLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = K_COMMA;


    // /Users/Robert/src/MiPal/GUNao/posix/gufsm/qfsm2gu/../LANGUAGE/SimpleCLexer.g:44:9: ( ',' )
    // /Users/Robert/src/MiPal/GUNao/posix/gufsm/qfsm2gu/../LANGUAGE/SimpleCLexer.g:44:11: ','
    {
        MATCHC(',');
        if  (HASEXCEPTION())
        {
            goto ruleK_COMMAEx;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleK_COMMAEx; /* Prevent compiler warnings */
    ruleK_COMMAEx: ;

}
// $ANTLR end K_COMMA

//   Comes from: 45:13: ( ';' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start K_SEMICOLON
 *
 * Looks to match the characters the constitute the token K_SEMICOLON
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mK_SEMICOLON(pSimpleCLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = K_SEMICOLON;


    // /Users/Robert/src/MiPal/GUNao/posix/gufsm/qfsm2gu/../LANGUAGE/SimpleCLexer.g:45:13: ( ';' )
    // /Users/Robert/src/MiPal/GUNao/posix/gufsm/qfsm2gu/../LANGUAGE/SimpleCLexer.g:45:15: ';'
    {
        MATCHC(';');
        if  (HASEXCEPTION())
        {
            goto ruleK_SEMICOLONEx;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleK_SEMICOLONEx; /* Prevent compiler warnings */
    ruleK_SEMICOLONEx: ;

}
// $ANTLR end K_SEMICOLON

//   Comes from: 46:8: ( '<' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start K_LT
 *
 * Looks to match the characters the constitute the token K_LT
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mK_LT(pSimpleCLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = K_LT;


    // /Users/Robert/src/MiPal/GUNao/posix/gufsm/qfsm2gu/../LANGUAGE/SimpleCLexer.g:46:8: ( '<' )
    // /Users/Robert/src/MiPal/GUNao/posix/gufsm/qfsm2gu/../LANGUAGE/SimpleCLexer.g:46:10: '<'
    {
        MATCHC('<');
        if  (HASEXCEPTION())
        {
            goto ruleK_LTEx;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleK_LTEx; /* Prevent compiler warnings */
    ruleK_LTEx: ;

}
// $ANTLR end K_LT

//   Comes from: 47:8: ( '=' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start K_EQ
 *
 * Looks to match the characters the constitute the token K_EQ
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mK_EQ(pSimpleCLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = K_EQ;


    // /Users/Robert/src/MiPal/GUNao/posix/gufsm/qfsm2gu/../LANGUAGE/SimpleCLexer.g:47:8: ( '=' )
    // /Users/Robert/src/MiPal/GUNao/posix/gufsm/qfsm2gu/../LANGUAGE/SimpleCLexer.g:47:10: '='
    {
        MATCHC('=');
        if  (HASEXCEPTION())
        {
            goto ruleK_EQEx;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleK_EQEx; /* Prevent compiler warnings */
    ruleK_EQEx: ;

}
// $ANTLR end K_EQ

//   Comes from: 48:8: ( '==' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start K_EQEQ
 *
 * Looks to match the characters the constitute the token K_EQEQ
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mK_EQEQ(pSimpleCLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = K_EQEQ;


    // /Users/Robert/src/MiPal/GUNao/posix/gufsm/qfsm2gu/../LANGUAGE/SimpleCLexer.g:48:8: ( '==' )
    // /Users/Robert/src/MiPal/GUNao/posix/gufsm/qfsm2gu/../LANGUAGE/SimpleCLexer.g:48:10: '=='
    {
        MATCHS(lit_7);
        if  (HASEXCEPTION())
        {
            goto ruleK_EQEQEx;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleK_EQEQEx; /* Prevent compiler warnings */
    ruleK_EQEQEx: ;

}
// $ANTLR end K_EQEQ

//   Comes from: 49:9: ( '&&' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start K_ANDAND
 *
 * Looks to match the characters the constitute the token K_ANDAND
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mK_ANDAND(pSimpleCLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = K_ANDAND;


    // /Users/Robert/src/MiPal/GUNao/posix/gufsm/qfsm2gu/../LANGUAGE/SimpleCLexer.g:49:9: ( '&&' )
    // /Users/Robert/src/MiPal/GUNao/posix/gufsm/qfsm2gu/../LANGUAGE/SimpleCLexer.g:49:11: '&&'
    {
        MATCHS(lit_8);
        if  (HASEXCEPTION())
        {
            goto ruleK_ANDANDEx;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleK_ANDANDEx; /* Prevent compiler warnings */
    ruleK_ANDANDEx: ;

}
// $ANTLR end K_ANDAND

//   Comes from: 50:8: ( '||' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start K_OROR
 *
 * Looks to match the characters the constitute the token K_OROR
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mK_OROR(pSimpleCLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = K_OROR;


    // /Users/Robert/src/MiPal/GUNao/posix/gufsm/qfsm2gu/../LANGUAGE/SimpleCLexer.g:50:8: ( '||' )
    // /Users/Robert/src/MiPal/GUNao/posix/gufsm/qfsm2gu/../LANGUAGE/SimpleCLexer.g:50:10: '||'
    {
        MATCHS(lit_9);
        if  (HASEXCEPTION())
        {
            goto ruleK_OROREx;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleK_OROREx; /* Prevent compiler warnings */
    ruleK_OROREx: ;

}
// $ANTLR end K_OROR

//   Comes from: 51:7: ( '!' | '~' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start K_NOT
 *
 * Looks to match the characters the constitute the token K_NOT
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mK_NOT(pSimpleCLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = K_NOT;


    // /Users/Robert/src/MiPal/GUNao/posix/gufsm/qfsm2gu/../LANGUAGE/SimpleCLexer.g:51:7: ( '!' | '~' )
    // /Users/Robert/src/MiPal/GUNao/posix/gufsm/qfsm2gu/../LANGUAGE/SimpleCLexer.g:
    {
        if ( LA(1) == '!' || LA(1) == '~' )
        {
            CONSUME();
        }
        else
        {
            CONSTRUCTEX();
            EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
            EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

            LRECOVER();
            goto ruleK_NOTEx;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleK_NOTEx; /* Prevent compiler warnings */
    ruleK_NOTEx: ;

}
// $ANTLR end K_NOT

//   Comes from: 52:10: ( '{' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start K_LCURLY
 *
 * Looks to match the characters the constitute the token K_LCURLY
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mK_LCURLY(pSimpleCLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = K_LCURLY;


    // /Users/Robert/src/MiPal/GUNao/posix/gufsm/qfsm2gu/../LANGUAGE/SimpleCLexer.g:52:10: ( '{' )
    // /Users/Robert/src/MiPal/GUNao/posix/gufsm/qfsm2gu/../LANGUAGE/SimpleCLexer.g:52:12: '{'
    {
        MATCHC('{');
        if  (HASEXCEPTION())
        {
            goto ruleK_LCURLYEx;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleK_LCURLYEx; /* Prevent compiler warnings */
    ruleK_LCURLYEx: ;

}
// $ANTLR end K_LCURLY

//   Comes from: 53:10: ( '}' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start K_RCURLY
 *
 * Looks to match the characters the constitute the token K_RCURLY
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mK_RCURLY(pSimpleCLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = K_RCURLY;


    // /Users/Robert/src/MiPal/GUNao/posix/gufsm/qfsm2gu/../LANGUAGE/SimpleCLexer.g:53:10: ( '}' )
    // /Users/Robert/src/MiPal/GUNao/posix/gufsm/qfsm2gu/../LANGUAGE/SimpleCLexer.g:53:12: '}'
    {
        MATCHC('}');
        if  (HASEXCEPTION())
        {
            goto ruleK_RCURLYEx;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleK_RCURLYEx; /* Prevent compiler warnings */
    ruleK_RCURLYEx: ;

}
// $ANTLR end K_RCURLY

//   Comes from: 55:5: ( ( ' ' | '\\t' | '\\r' | '\\n' )+ )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start WS
 *
 * Looks to match the characters the constitute the token WS
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mWS(pSimpleCLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = WS;


    // /Users/Robert/src/MiPal/GUNao/posix/gufsm/qfsm2gu/../LANGUAGE/SimpleCLexer.g:55:5: ( ( ' ' | '\\t' | '\\r' | '\\n' )+ )
    // /Users/Robert/src/MiPal/GUNao/posix/gufsm/qfsm2gu/../LANGUAGE/SimpleCLexer.g:55:9: ( ' ' | '\\t' | '\\r' | '\\n' )+
    {
        // /Users/Robert/src/MiPal/GUNao/posix/gufsm/qfsm2gu/../LANGUAGE/SimpleCLexer.g:55:9: ( ' ' | '\\t' | '\\r' | '\\n' )+
        {
            int cnt5=0;

            for (;;)
            {
                int alt5=2;
        	switch ( LA(1) )
        	{
        	case '\t':
        	case '\n':
        	case '\r':
        	case ' ':
        		{
        			alt5=1;
        		}
        	    break;

        	}

        	switch (alt5)
        	{
        	    case 1:
        	        // /Users/Robert/src/MiPal/GUNao/posix/gufsm/qfsm2gu/../LANGUAGE/SimpleCLexer.g:
        	        {
        	            if ( ((LA(1) >= '\t') && (LA(1) <= '\n')) || LA(1) == '\r' || LA(1) == ' ' )
        	            {
        	                CONSUME();
        	            }
        	            else
        	            {
        	                CONSTRUCTEX();
        	                EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
        	                EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

        	                LRECOVER();
        	                goto ruleWSEx;
        	            }


        	        }
        	        break;

        	    default:

        		if ( cnt5 >= 1 )
        		{
        		    goto loop5;
        		}
        		/* mismatchedSetEx()
        		 */
        		CONSTRUCTEX();
        		EXCEPTION->type = ANTLR3_EARLY_EXIT_EXCEPTION;
        		EXCEPTION->name = (void *)ANTLR3_EARLY_EXIT_NAME;


        		goto ruleWSEx;
        	}
        	cnt5++;
            }
            loop5: ;	/* Jump to here if this rule does not match */
        }

        {
             LEXSTATE->channel=HIDDEN; 
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleWSEx; /* Prevent compiler warnings */
    ruleWSEx: ;

}
// $ANTLR end WS

/** This is the entry point in to the lexer from an object that
 *  wants to generate the next token, such as a pCOMMON_TOKEN_STREAM
 */
static void
mTokens(pSimpleCLexer ctx)
{
    {
        //  /Users/Robert/src/MiPal/GUNao/posix/gufsm/qfsm2gu/../LANGUAGE/SimpleCLexer.g:1:8: ( EscapeSequence | STRING_LITERAL | EOL | ONENTRY | ONEXIT | K_FOR | K_CHAR | K_INT_TYPE | K_VOID | K_ID | K_INT | K_LCURVE | K_RCURVE | K_PLUS | K_MINUS | K_COMMA | K_SEMICOLON | K_LT | K_EQ | K_EQEQ | K_ANDAND | K_OROR | K_NOT | K_LCURLY | K_RCURLY | WS )

        ANTLR3_UINT32 alt6;

        alt6=26;

        switch ( LA(1) )
        {
        case '\\':
        	{
        		alt6=1;
        	}
            break;
        case '"':
        	{
        		alt6=2;
        	}
            break;
        case '\n':
        	{
        		switch ( LA(2) )
        		{
        		case '\t':
        		case '\n':
        		case '\r':
        		case ' ':
        			{
        				alt6=26;
        			}
        		    break;

        		default:
        		    alt6=3;
        		}

        	}
            break;
        case 'O':
        	{
        		switch ( LA(2) )
        		{
        		case 'n':
        			{
        				switch ( LA(3) )
        				{
        				case 'E':
        					{
        						switch ( LA(4) )
        						{
        						case 'n':
        							{
        								switch ( LA(5) )
        								{
        								case 't':
        									{
        										switch ( LA(6) )
        										{
        										case 'r':
        											{
        												switch ( LA(7) )
        												{
        												case 'y':
        													{
        														switch ( LA(8) )
        														{
        														case '0':
        														case '1':
        														case '2':
        														case '3':
        														case '4':
        														case '5':
        														case '6':
        														case '7':
        														case '8':
        														case '9':
        														case 'A':
        														case 'B':
        														case 'C':
        														case 'D':
        														case 'E':
        														case 'F':
        														case 'G':
        														case 'H':
        														case 'I':
        														case 'J':
        														case 'K':
        														case 'L':
        														case 'M':
        														case 'N':
        														case 'O':
        														case 'P':
        														case 'Q':
        														case 'R':
        														case 'S':
        														case 'T':
        														case 'U':
        														case 'V':
        														case 'W':
        														case 'X':
        														case 'Y':
        														case 'Z':
        														case '_':
        														case 'a':
        														case 'b':
        														case 'c':
        														case 'd':
        														case 'e':
        														case 'f':
        														case 'g':
        														case 'h':
        														case 'i':
        														case 'j':
        														case 'k':
        														case 'l':
        														case 'm':
        														case 'n':
        														case 'o':
        														case 'p':
        														case 'q':
        														case 'r':
        														case 's':
        														case 't':
        														case 'u':
        														case 'v':
        														case 'w':
        														case 'x':
        														case 'y':
        														case 'z':
        															{
        																alt6=10;
        															}
        														    break;

        														default:
        														    alt6=4;
        														}

        													}
        												    break;

        												default:
        												    alt6=10;
        												}

        											}
        										    break;

        										default:
        										    alt6=10;
        										}

        									}
        								    break;

        								default:
        								    alt6=10;
        								}

        							}
        						    break;
        						case 'x':
        							{
        								switch ( LA(5) )
        								{
        								case 'i':
        									{
        										switch ( LA(6) )
        										{
        										case 't':
        											{
        												switch ( LA(7) )
        												{
        												case '0':
        												case '1':
        												case '2':
        												case '3':
        												case '4':
        												case '5':
        												case '6':
        												case '7':
        												case '8':
        												case '9':
        												case 'A':
        												case 'B':
        												case 'C':
        												case 'D':
        												case 'E':
        												case 'F':
        												case 'G':
        												case 'H':
        												case 'I':
        												case 'J':
        												case 'K':
        												case 'L':
        												case 'M':
        												case 'N':
        												case 'O':
        												case 'P':
        												case 'Q':
        												case 'R':
        												case 'S':
        												case 'T':
        												case 'U':
        												case 'V':
        												case 'W':
        												case 'X':
        												case 'Y':
        												case 'Z':
        												case '_':
        												case 'a':
        												case 'b':
        												case 'c':
        												case 'd':
        												case 'e':
        												case 'f':
        												case 'g':
        												case 'h':
        												case 'i':
        												case 'j':
        												case 'k':
        												case 'l':
        												case 'm':
        												case 'n':
        												case 'o':
        												case 'p':
        												case 'q':
        												case 'r':
        												case 's':
        												case 't':
        												case 'u':
        												case 'v':
        												case 'w':
        												case 'x':
        												case 'y':
        												case 'z':
        													{
        														alt6=10;
        													}
        												    break;

        												default:
        												    alt6=5;
        												}

        											}
        										    break;

        										default:
        										    alt6=10;
        										}

        									}
        								    break;

        								default:
        								    alt6=10;
        								}

        							}
        						    break;

        						default:
        						    alt6=10;
        						}

        					}
        				    break;

        				default:
        				    alt6=10;
        				}

        			}
        		    break;

        		default:
        		    alt6=10;
        		}

        	}
            break;
        case 'f':
        	{
        		switch ( LA(2) )
        		{
        		case 'o':
        			{
        				switch ( LA(3) )
        				{
        				case 'r':
        					{
        						switch ( LA(4) )
        						{
        						case '0':
        						case '1':
        						case '2':
        						case '3':
        						case '4':
        						case '5':
        						case '6':
        						case '7':
        						case '8':
        						case '9':
        						case 'A':
        						case 'B':
        						case 'C':
        						case 'D':
        						case 'E':
        						case 'F':
        						case 'G':
        						case 'H':
        						case 'I':
        						case 'J':
        						case 'K':
        						case 'L':
        						case 'M':
        						case 'N':
        						case 'O':
        						case 'P':
        						case 'Q':
        						case 'R':
        						case 'S':
        						case 'T':
        						case 'U':
        						case 'V':
        						case 'W':
        						case 'X':
        						case 'Y':
        						case 'Z':
        						case '_':
        						case 'a':
        						case 'b':
        						case 'c':
        						case 'd':
        						case 'e':
        						case 'f':
        						case 'g':
        						case 'h':
        						case 'i':
        						case 'j':
        						case 'k':
        						case 'l':
        						case 'm':
        						case 'n':
        						case 'o':
        						case 'p':
        						case 'q':
        						case 'r':
        						case 's':
        						case 't':
        						case 'u':
        						case 'v':
        						case 'w':
        						case 'x':
        						case 'y':
        						case 'z':
        							{
        								alt6=10;
        							}
        						    break;

        						default:
        						    alt6=6;
        						}

        					}
        				    break;

        				default:
        				    alt6=10;
        				}

        			}
        		    break;

        		default:
        		    alt6=10;
        		}

        	}
            break;
        case 'c':
        	{
        		switch ( LA(2) )
        		{
        		case 'h':
        			{
        				switch ( LA(3) )
        				{
        				case 'a':
        					{
        						switch ( LA(4) )
        						{
        						case 'r':
        							{
        								switch ( LA(5) )
        								{
        								case '0':
        								case '1':
        								case '2':
        								case '3':
        								case '4':
        								case '5':
        								case '6':
        								case '7':
        								case '8':
        								case '9':
        								case 'A':
        								case 'B':
        								case 'C':
        								case 'D':
        								case 'E':
        								case 'F':
        								case 'G':
        								case 'H':
        								case 'I':
        								case 'J':
        								case 'K':
        								case 'L':
        								case 'M':
        								case 'N':
        								case 'O':
        								case 'P':
        								case 'Q':
        								case 'R':
        								case 'S':
        								case 'T':
        								case 'U':
        								case 'V':
        								case 'W':
        								case 'X':
        								case 'Y':
        								case 'Z':
        								case '_':
        								case 'a':
        								case 'b':
        								case 'c':
        								case 'd':
        								case 'e':
        								case 'f':
        								case 'g':
        								case 'h':
        								case 'i':
        								case 'j':
        								case 'k':
        								case 'l':
        								case 'm':
        								case 'n':
        								case 'o':
        								case 'p':
        								case 'q':
        								case 'r':
        								case 's':
        								case 't':
        								case 'u':
        								case 'v':
        								case 'w':
        								case 'x':
        								case 'y':
        								case 'z':
        									{
        										alt6=10;
        									}
        								    break;

        								default:
        								    alt6=7;
        								}

        							}
        						    break;

        						default:
        						    alt6=10;
        						}

        					}
        				    break;

        				default:
        				    alt6=10;
        				}

        			}
        		    break;

        		default:
        		    alt6=10;
        		}

        	}
            break;
        case 'i':
        	{
        		switch ( LA(2) )
        		{
        		case 'n':
        			{
        				switch ( LA(3) )
        				{
        				case 't':
        					{
        						switch ( LA(4) )
        						{
        						case '0':
        						case '1':
        						case '2':
        						case '3':
        						case '4':
        						case '5':
        						case '6':
        						case '7':
        						case '8':
        						case '9':
        						case 'A':
        						case 'B':
        						case 'C':
        						case 'D':
        						case 'E':
        						case 'F':
        						case 'G':
        						case 'H':
        						case 'I':
        						case 'J':
        						case 'K':
        						case 'L':
        						case 'M':
        						case 'N':
        						case 'O':
        						case 'P':
        						case 'Q':
        						case 'R':
        						case 'S':
        						case 'T':
        						case 'U':
        						case 'V':
        						case 'W':
        						case 'X':
        						case 'Y':
        						case 'Z':
        						case '_':
        						case 'a':
        						case 'b':
        						case 'c':
        						case 'd':
        						case 'e':
        						case 'f':
        						case 'g':
        						case 'h':
        						case 'i':
        						case 'j':
        						case 'k':
        						case 'l':
        						case 'm':
        						case 'n':
        						case 'o':
        						case 'p':
        						case 'q':
        						case 'r':
        						case 's':
        						case 't':
        						case 'u':
        						case 'v':
        						case 'w':
        						case 'x':
        						case 'y':
        						case 'z':
        							{
        								alt6=10;
        							}
        						    break;

        						default:
        						    alt6=8;
        						}

        					}
        				    break;

        				default:
        				    alt6=10;
        				}

        			}
        		    break;

        		default:
        		    alt6=10;
        		}

        	}
            break;
        case 'v':
        	{
        		switch ( LA(2) )
        		{
        		case 'o':
        			{
        				switch ( LA(3) )
        				{
        				case 'i':
        					{
        						switch ( LA(4) )
        						{
        						case 'd':
        							{
        								switch ( LA(5) )
        								{
        								case '0':
        								case '1':
        								case '2':
        								case '3':
        								case '4':
        								case '5':
        								case '6':
        								case '7':
        								case '8':
        								case '9':
        								case 'A':
        								case 'B':
        								case 'C':
        								case 'D':
        								case 'E':
        								case 'F':
        								case 'G':
        								case 'H':
        								case 'I':
        								case 'J':
        								case 'K':
        								case 'L':
        								case 'M':
        								case 'N':
        								case 'O':
        								case 'P':
        								case 'Q':
        								case 'R':
        								case 'S':
        								case 'T':
        								case 'U':
        								case 'V':
        								case 'W':
        								case 'X':
        								case 'Y':
        								case 'Z':
        								case '_':
        								case 'a':
        								case 'b':
        								case 'c':
        								case 'd':
        								case 'e':
        								case 'f':
        								case 'g':
        								case 'h':
        								case 'i':
        								case 'j':
        								case 'k':
        								case 'l':
        								case 'm':
        								case 'n':
        								case 'o':
        								case 'p':
        								case 'q':
        								case 'r':
        								case 's':
        								case 't':
        								case 'u':
        								case 'v':
        								case 'w':
        								case 'x':
        								case 'y':
        								case 'z':
        									{
        										alt6=10;
        									}
        								    break;

        								default:
        								    alt6=9;
        								}

        							}
        						    break;

        						default:
        						    alt6=10;
        						}

        					}
        				    break;

        				default:
        				    alt6=10;
        				}

        			}
        		    break;

        		default:
        		    alt6=10;
        		}

        	}
            break;
        case 'A':
        case 'B':
        case 'C':
        case 'D':
        case 'E':
        case 'F':
        case 'G':
        case 'H':
        case 'I':
        case 'J':
        case 'K':
        case 'L':
        case 'M':
        case 'N':
        case 'P':
        case 'Q':
        case 'R':
        case 'S':
        case 'T':
        case 'U':
        case 'V':
        case 'W':
        case 'X':
        case 'Y':
        case 'Z':
        case '_':
        case 'a':
        case 'b':
        case 'd':
        case 'e':
        case 'g':
        case 'h':
        case 'j':
        case 'k':
        case 'l':
        case 'm':
        case 'n':
        case 'o':
        case 'p':
        case 'q':
        case 'r':
        case 's':
        case 't':
        case 'u':
        case 'w':
        case 'x':
        case 'y':
        case 'z':
        	{
        		alt6=10;
        	}
            break;
        case '0':
        case '1':
        case '2':
        case '3':
        case '4':
        case '5':
        case '6':
        case '7':
        case '8':
        case '9':
        	{
        		alt6=11;
        	}
            break;
        case '(':
        	{
        		alt6=12;
        	}
            break;
        case ')':
        	{
        		alt6=13;
        	}
            break;
        case '+':
        	{
        		alt6=14;
        	}
            break;
        case '-':
        	{
        		alt6=15;
        	}
            break;
        case ',':
        	{
        		alt6=16;
        	}
            break;
        case ';':
        	{
        		alt6=17;
        	}
            break;
        case '<':
        	{
        		alt6=18;
        	}
            break;
        case '=':
        	{
        		switch ( LA(2) )
        		{
        		case '=':
        			{
        				alt6=20;
        			}
        		    break;

        		default:
        		    alt6=19;
        		}

        	}
            break;
        case '&':
        	{
        		alt6=21;
        	}
            break;
        case '|':
        	{
        		alt6=22;
        	}
            break;
        case '!':
        case '~':
        	{
        		alt6=23;
        	}
            break;
        case '{':
        	{
        		alt6=24;
        	}
            break;
        case '}':
        	{
        		alt6=25;
        	}
            break;
        case '\t':
        case '\r':
        case ' ':
        	{
        		alt6=26;
        	}
            break;

        default:
            CONSTRUCTEX();
            EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
            EXCEPTION->message      = (void *)"";
            EXCEPTION->decisionNum  = 6;
            EXCEPTION->state        = 0;


            goto ruleTokensEx;

        }

        switch (alt6)
        {
    	case 1:
    	    // /Users/Robert/src/MiPal/GUNao/posix/gufsm/qfsm2gu/../LANGUAGE/SimpleCLexer.g:1:10: EscapeSequence
    	    {
    	        /* 1:10: EscapeSequence */
    	        mEscapeSequence(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 2:
    	    // /Users/Robert/src/MiPal/GUNao/posix/gufsm/qfsm2gu/../LANGUAGE/SimpleCLexer.g:1:25: STRING_LITERAL
    	    {
    	        /* 1:25: STRING_LITERAL */
    	        mSTRING_LITERAL(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 3:
    	    // /Users/Robert/src/MiPal/GUNao/posix/gufsm/qfsm2gu/../LANGUAGE/SimpleCLexer.g:1:40: EOL
    	    {
    	        /* 1:40: EOL */
    	        mEOL(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 4:
    	    // /Users/Robert/src/MiPal/GUNao/posix/gufsm/qfsm2gu/../LANGUAGE/SimpleCLexer.g:1:44: ONENTRY
    	    {
    	        /* 1:44: ONENTRY */
    	        mONENTRY(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 5:
    	    // /Users/Robert/src/MiPal/GUNao/posix/gufsm/qfsm2gu/../LANGUAGE/SimpleCLexer.g:1:52: ONEXIT
    	    {
    	        /* 1:52: ONEXIT */
    	        mONEXIT(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 6:
    	    // /Users/Robert/src/MiPal/GUNao/posix/gufsm/qfsm2gu/../LANGUAGE/SimpleCLexer.g:1:59: K_FOR
    	    {
    	        /* 1:59: K_FOR */
    	        mK_FOR(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 7:
    	    // /Users/Robert/src/MiPal/GUNao/posix/gufsm/qfsm2gu/../LANGUAGE/SimpleCLexer.g:1:65: K_CHAR
    	    {
    	        /* 1:65: K_CHAR */
    	        mK_CHAR(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 8:
    	    // /Users/Robert/src/MiPal/GUNao/posix/gufsm/qfsm2gu/../LANGUAGE/SimpleCLexer.g:1:72: K_INT_TYPE
    	    {
    	        /* 1:72: K_INT_TYPE */
    	        mK_INT_TYPE(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 9:
    	    // /Users/Robert/src/MiPal/GUNao/posix/gufsm/qfsm2gu/../LANGUAGE/SimpleCLexer.g:1:83: K_VOID
    	    {
    	        /* 1:83: K_VOID */
    	        mK_VOID(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 10:
    	    // /Users/Robert/src/MiPal/GUNao/posix/gufsm/qfsm2gu/../LANGUAGE/SimpleCLexer.g:1:90: K_ID
    	    {
    	        /* 1:90: K_ID */
    	        mK_ID(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 11:
    	    // /Users/Robert/src/MiPal/GUNao/posix/gufsm/qfsm2gu/../LANGUAGE/SimpleCLexer.g:1:95: K_INT
    	    {
    	        /* 1:95: K_INT */
    	        mK_INT(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 12:
    	    // /Users/Robert/src/MiPal/GUNao/posix/gufsm/qfsm2gu/../LANGUAGE/SimpleCLexer.g:1:101: K_LCURVE
    	    {
    	        /* 1:101: K_LCURVE */
    	        mK_LCURVE(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 13:
    	    // /Users/Robert/src/MiPal/GUNao/posix/gufsm/qfsm2gu/../LANGUAGE/SimpleCLexer.g:1:110: K_RCURVE
    	    {
    	        /* 1:110: K_RCURVE */
    	        mK_RCURVE(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 14:
    	    // /Users/Robert/src/MiPal/GUNao/posix/gufsm/qfsm2gu/../LANGUAGE/SimpleCLexer.g:1:119: K_PLUS
    	    {
    	        /* 1:119: K_PLUS */
    	        mK_PLUS(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 15:
    	    // /Users/Robert/src/MiPal/GUNao/posix/gufsm/qfsm2gu/../LANGUAGE/SimpleCLexer.g:1:126: K_MINUS
    	    {
    	        /* 1:126: K_MINUS */
    	        mK_MINUS(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 16:
    	    // /Users/Robert/src/MiPal/GUNao/posix/gufsm/qfsm2gu/../LANGUAGE/SimpleCLexer.g:1:134: K_COMMA
    	    {
    	        /* 1:134: K_COMMA */
    	        mK_COMMA(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 17:
    	    // /Users/Robert/src/MiPal/GUNao/posix/gufsm/qfsm2gu/../LANGUAGE/SimpleCLexer.g:1:142: K_SEMICOLON
    	    {
    	        /* 1:142: K_SEMICOLON */
    	        mK_SEMICOLON(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 18:
    	    // /Users/Robert/src/MiPal/GUNao/posix/gufsm/qfsm2gu/../LANGUAGE/SimpleCLexer.g:1:154: K_LT
    	    {
    	        /* 1:154: K_LT */
    	        mK_LT(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 19:
    	    // /Users/Robert/src/MiPal/GUNao/posix/gufsm/qfsm2gu/../LANGUAGE/SimpleCLexer.g:1:159: K_EQ
    	    {
    	        /* 1:159: K_EQ */
    	        mK_EQ(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 20:
    	    // /Users/Robert/src/MiPal/GUNao/posix/gufsm/qfsm2gu/../LANGUAGE/SimpleCLexer.g:1:164: K_EQEQ
    	    {
    	        /* 1:164: K_EQEQ */
    	        mK_EQEQ(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 21:
    	    // /Users/Robert/src/MiPal/GUNao/posix/gufsm/qfsm2gu/../LANGUAGE/SimpleCLexer.g:1:171: K_ANDAND
    	    {
    	        /* 1:171: K_ANDAND */
    	        mK_ANDAND(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 22:
    	    // /Users/Robert/src/MiPal/GUNao/posix/gufsm/qfsm2gu/../LANGUAGE/SimpleCLexer.g:1:180: K_OROR
    	    {
    	        /* 1:180: K_OROR */
    	        mK_OROR(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 23:
    	    // /Users/Robert/src/MiPal/GUNao/posix/gufsm/qfsm2gu/../LANGUAGE/SimpleCLexer.g:1:187: K_NOT
    	    {
    	        /* 1:187: K_NOT */
    	        mK_NOT(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 24:
    	    // /Users/Robert/src/MiPal/GUNao/posix/gufsm/qfsm2gu/../LANGUAGE/SimpleCLexer.g:1:193: K_LCURLY
    	    {
    	        /* 1:193: K_LCURLY */
    	        mK_LCURLY(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 25:
    	    // /Users/Robert/src/MiPal/GUNao/posix/gufsm/qfsm2gu/../LANGUAGE/SimpleCLexer.g:1:202: K_RCURLY
    	    {
    	        /* 1:202: K_RCURLY */
    	        mK_RCURLY(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 26:
    	    // /Users/Robert/src/MiPal/GUNao/posix/gufsm/qfsm2gu/../LANGUAGE/SimpleCLexer.g:1:211: WS
    	    {
    	        /* 1:211: WS */
    	        mWS(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;

        }
    }


    goto ruleTokensEx; /* Prevent compiler warnings */
ruleTokensEx: ;
}

/* =========================================================================
 * Lexer matching rules end.
 * =========================================================================
 */
/* End of Lexer code
 * ================================================
 * ================================================
 */


/* End of code
 * =============================================================================
 */
