#
#	$Id$
#
# Makefile for pre- and cross-compiling .machine files
#
MACHINES=PingPongCLFSM_META

.include "../../../../mk/fsm.mk"	# comes first: required for compiling state machines

.include "../../../../mk/mipal.mk"	# comes last!
