.\"Modified from man(1) of FreeBSD, the NetBSD mdoc.template, and mdoc.samples.
.\"See Also:
.\"man mdoc.samples for a complete listing of options
.\"man mdoc for the short list of editing options
.\"/usr/share/misc/mdoc.template
.Dd 18/03/11               \" DATE 
.Dt qfsm2gu 1      \" Program name and manual section number 
.Os Darwin
.Sh NAME                 \" Section Header - required - don't modify 
.Nm qfsm2gu
.Nd Qfsm to GU A and T state machine file converter
.Sh SYNOPSIS             \" Section Header - required - don't modify
.Nm
.Op Ar                   \" [file ...]
.Sh DESCRIPTION          \" Section Header - required - don't modify
The
.Nm
command line tool converts the passed files to corresponding A and T
files in the current directory.  These A and T files are suitable as
input for the GU state machine behaviour interpreter.
.Sh SEE ALSO 
.\" List links in ascending order by section, alphabetically within a section.
.\" Please do not reference files that do not exist without filing a bug report
.Xr qfsm 1
.\" .Sh HISTORY           \" Document history if command behaves in a unique manner
