// Generated by CLMetaGen. Do not modify.
#include "CLMetaState.h"
#include "PingPongCLFSM_META_MetaMachine.h"
#include "PingPongCLFSM_META_Properties.h"
#include "State_Ping_Properties.h"
#include "State_Pong_Properties.h"
using namespace std;
using namespace FSM;
using namespace CLReflect;
using namespace PingPongCLFSM_META_namespace;
extern "C"
{
	CLMetaMachine* FSM::PingPongCLFSM_META_namespace::Create()
	{
		CLMetaMachine* meta = new CLMetaMachine("PingPongCLFSM_META", "PingPongCLFSM_META");
		
		// Machine properties
		shared_ptr<Meta_Machine_currentState> property_0(new Meta_Machine_currentState());
		meta->addProperty(property_0);
		
		// State creation
		// State: Ping
		shared_ptr<CLMetaState> state_0(new CLMetaState("Ping"));
		meta->addState(state_0);
		
		// State: Pong
		shared_ptr<CLMetaState> state_1(new CLMetaState("Pong"));
		meta->addState(state_1);
		
		return meta;
	}
}
