#
#	$Id$
#
# Makefile for pre- and cross-compiling .machine files
#

MACHINES=SMSeeker 

.include "../../../../../../mk/fsm.mk"	# comes first: required for compiling state machines

SPECIFIC_CPPFLAGS+=-fblocks

.include "../../../../../../mk/mipal.mk"	# comes last!
